import type { ProjectContext } from '../../ai/types';

/**
 * Projectscopestatement Template generates the content for the Projectscopestatement document.
 */
export class ProjectscopestatementTemplate {
  constructor(private context: ProjectContext) {}

  /**
   * Build the markdown content for Project Scope Statement
   */
  generateContent(): string {
    return `# Project Scope Statement

**Generated by Requirements Gathering Agent v2.1.2**  
**Category:** scope-management  
**Generated:** ${new Date().toISOString()}  
**Description:** PMBOK Project Scope Statement with Enhanced Explicit Exclusions

---

## Document Purpose

This Project Scope Statement provides a comprehensive definition of project scope, deliverables, boundaries, and explicit exclusions. It serves as the foundational document for scope management and change control throughout the project lifecycle.

**PMBOK Reference:** 5.3.3.1 - Project Scope Statement

---

## 1. Project Overview

**Project Name:** ${this.context.projectName || 'Untitled Project'}
**Project Type:** ${this.context.projectType || 'Not specified'}
**Project Description:** ${this.context.description || 'No description provided'}

---

## 2. Project Scope Description

### 2.1 Project Purpose and Justification
[Define why this project is being undertaken and its business value]

### 2.2 Product Scope Description  
[Describe what product/service will be created]

### 2.3 Project Objectives
[List measurable objectives that define project success]

---

## 3. Project Deliverables

### 3.1 Primary Deliverables
[List main deliverables that will be produced]

### 3.2 Secondary Deliverables  
[Identify supporting deliverables like documentation, training, etc.]

### 3.3 Deliverable Acceptance Criteria
[Define measurable acceptance criteria for each deliverable]

---

## 4. Scope Boundaries

### 4.1 In Scope
[Define what IS included in this project]

### 4.2 Explicit Exclusions (Out of Scope)
[Define what is explicitly NOT included to prevent scope creep]

#### 4.2.1 Functional Exclusions
- [List specific features or capabilities excluded]

#### 4.2.2 Technical Exclusions  
- [Define technical components or platforms excluded]

#### 4.2.3 Business Process Exclusions
- [Identify business processes or organizational changes excluded]

#### 4.2.4 Data and Content Exclusions
- [Specify data migration or content creation tasks excluded]

#### 4.2.5 Infrastructure and Environment Exclusions
- [Define infrastructure or environment setup excluded]

#### 4.2.6 Support and Maintenance Exclusions
- [Clarify ongoing support or maintenance excluded]

#### 4.2.7 Future Phase Exclusions
- [Identify features planned for future releases]

### 4.3 Scope Clarifications
[Address common areas of confusion or potential misinterpretation]

---

## 5. Project Requirements

### 5.1 Functional Requirements
[Define what the system must do]

### 5.2 Non-Functional Requirements
[Define performance, security, usability requirements]

### 5.3 Quality Requirements
[Define quality standards and criteria]

---

## 6. Project Constraints

### 6.1 Technical Constraints
[List technical limitations or requirements]

### 6.2 Resource Constraints  
[Define budget, timeline, and personnel constraints]

### 6.3 Environmental Constraints
[List platform, integration, or compliance constraints]

---

## 7. Project Assumptions

### 7.1 Technical Assumptions
[List technical assumptions]

### 7.2 Business Assumptions
[List business assumptions]

### 7.3 Resource Assumptions
[List resource and stakeholder assumptions]

---

## 8. Success Criteria and Acceptance Criteria

### 8.1 Project Success Criteria
[Define how project success will be measured]

### 8.2 Product Acceptance Criteria
[Define how deliverables will be accepted]

---

## 9. Scope Management Guidelines

### 9.1 Change Control Process
[Define how scope changes will be managed]

### 9.2 Exclusion Communication
[Ensure stakeholders understand what is excluded]

### 9.3 Scope Validation Process
[Define how scope will be validated with stakeholders]

---

*This document serves as the foundation for project scope management and should be reviewed and approved by all key stakeholders before project execution begins.*
`;
  }
}
