/*
 * Copyright (c) Microsoft Corporation. All rights reserved. Licensed under the MIT license.
 * See LICENSE in the project root for license information.
 */

/* global Office Word console */

/**
 * Insert a blue paragraph in Word when the add-in command is executed.
 * @param event
 */
export async function insertBlueParagraphInWord(event: Office.AddinCommands.Event) {
  try {
    await Word.run(async (context) => {
      const paragraph = context.document.body.insertParagraph("Hello World", Word.InsertLocation.end);
      paragraph.font.color = "blue";
      await context.sync();
    });
  } catch (error) {
    // Note: In a production add-in, notify the user through your add-in's UI.
    console.error(error);
  }

  // Be sure to indicate when the add-in command function is complete
  event.completed();
}

/**
 * Insert formatted text into the current document
 * @param event
 */
export async function insertFormattedText(event: Office.AddinCommands.Event) {
  try {
    await Word.run(async (context) => {
      // Insert a title
      const title = context.document.body.insertParagraph("ADPA Document", Word.InsertLocation.end);
      title.styleBuiltIn = Word.BuiltInStyleName.title;

      // Insert some content
      const content = context.document.body.insertParagraph(
        "This document was generated by the ADPA Office Add-in.",
        Word.InsertLocation.end
      );
      content.styleBuiltIn = Word.BuiltInStyleName.normal;

      await context.sync();
    });
  } catch (error) {
    console.error(error);
  }

  event.completed();
}

/**
 * Insert a simple table into the document
 * @param event
 */
export async function insertTable(event: Office.AddinCommands.Event) {
  try {
    await Word.run(async (context) => {
      // Insert a 3x3 table
      const table = context.document.body.insertTable(3, 3, Word.InsertLocation.end);

      // Add headers
      table.getCell(0, 0).value = "Project Phase";
      table.getCell(0, 1).value = "Duration";
      table.getCell(0, 2).value = "Status";

      // Add sample data
      table.getCell(1, 0).value = "Planning";
      table.getCell(1, 1).value = "2 weeks";
      table.getCell(1, 2).value = "Complete";

      table.getCell(2, 0).value = "Development";
      table.getCell(2, 1).value = "8 weeks";
      table.getCell(2, 2).value = "In Progress";

      // Style the header row
      const headerRow = table.rows.getFirst();
      headerRow.font.bold = true;
      headerRow.font.color = "white";
      headerRow.shadingColor = "#2F5F8F";

      await context.sync();
    });
  } catch (error) {
    console.error(error);
  }

  event.completed();
}
