/**
 * Database Template Interface
 * Generated by migration script
 */
export interface DatabaseTemplate {
    id: string;
    name: string;
    description: string;
    category: string;
    template_type: string;
    ai_instructions: string;
    prompt_template: string;
    generation_function: string;
    metadata: Record<string, any>;
    version: number;
    is_active: boolean;
    is_system: boolean;
    created_by: string;
    created_at: string;
    updated_at?: string;
}

export interface TemplateCategory {
    id: string;
    name: string;
    description: string;
    parent_category_id?: string;
    sort_order: number;
}

export interface TemplateSearchQuery {
    category?: string;
    template_type?: string;
    is_active?: boolean;
    is_system?: boolean;
    search_text?: string;
    limit?: number;
    offset?: number;
}

export interface CreateTemplateRequest {
    name: string;
    description: string;
    category: string;
    template_type?: string;
    ai_instructions: string;
    prompt_template: string;
    generation_function: string;
    metadata?: Record<string, any>;
    created_by: string;
}

export interface UpdateTemplateRequest {
    name?: string;
    description?: string;
    category?: string;
    ai_instructions?: string;
    prompt_template?: string;
    generation_function?: string;
    metadata?: Record<string, any>;
}

export interface TemplateValidationResult {
    valid: boolean;
    issues: string[];
    warnings?: string[];
}

export interface TemplateStats {
    total_templates: number;
    system_templates: number;
    user_templates: number;
    active_templates: number;
    categories: number;
    pmbok_templates: number;
}
