import type { ProjectContext } from '../../ai/types';

/**
 * StakeholderRegister Template - Enhanced with Cross-Document Intelligence
 * 
 * Generates a PMBOK-compliant Stakeholder Register that intelligently synthesizes
 * stakeholder information from User Personas, User Stories, and project context,
 * while providing educational placeholders for organizational data.
 */
export class StakeholderregisterTemplate {
  constructor(private context: ProjectContext) {}

  /**
   * Build the markdown content for Stakeholder Register with intelligent pre-population
   */
  generateContent(): string {
    const currentDate = new Date().toISOString();
    
    return `# Stakeholder Register

**Generated by:** ADPA (Automated Documentation Project Assistant)
**Category:** stakeholder-management
**Generated:** ${currentDate}
**Project:** ${this.context.projectName}
**PMBOK Reference:** 13.1.3.1

---

## Document Purpose

This Stakeholder Register identifies and documents detailed information about project stakeholders, their requirements, expectations, and influence levels. This document serves as the foundation for stakeholder engagement planning and communication strategy.

---

## 1. Stakeholder Identification Summary

*[AI Instruction: Analyze the User Personas and User Stories documents to extract and categorize all mentioned stakeholders. Include their roles, influence levels, and project interests.]*

### Primary Stakeholders (High Power, High Interest)
*[AI Instruction: Extract primary stakeholders from User Personas - these are typically the direct users and project sponsors mentioned in the personas.]*

### Secondary Stakeholders (Variable Power/Interest) 
*[AI Instruction: Infer secondary stakeholders from project context, user stories, and technical requirements.]*

---

## 2. Detailed Stakeholder Information

### Stakeholders Identified from Project Analysis

*[AI Instruction: For each stakeholder identified in User Personas and User Stories, create detailed entries using the template below. Extract as much information as possible from the persona descriptions.]*

| Stakeholder Name | Role/Title | Organization | Project Role | Contact Information | Power Level | Interest Level | Current Engagement | Desired Engagement |
|:---|:---|:---|:---|:---|:---|:---|:---|:---|
| *[Extract from User Personas]* | *[From Personas]* | *[From Context]* | *[Infer from Role]* | *[TBD - Organizational Input Required]* | *[Assess from Persona]* | *[Assess from Goals]* | *[Assess Current State]* | *[Recommend Target]* |

---

## 3. Organizational Stakeholders (Requires Organizational Input)

*[Educational Instruction: The following stakeholders are typically required for projects of this type but need to be confirmed and detailed using organizational data sources.]*

### Executive Stakeholders
*[Instruction: Consult organizational charts and identify the following executive stakeholders for this project:]*

- **Project Sponsor:** *[TBD - Identify from organizational hierarchy]*
- **Executive Sponsor:** *[TBD - Department head or VP level]*
- **Steering Committee Members:** *[TBD - Based on project scope and organizational structure]*

### Functional Stakeholders  
*[Instruction: Based on project requirements, identify stakeholders from the following departments:]*

- **IT Department:** *[TBD - IT Director, Security Officer, Infrastructure Team]*
- **Legal/Compliance:** *[TBD - If project involves data handling, contracts, or regulatory requirements]*
- **Finance:** *[TBD - Budget approval, cost tracking, ROI measurement]*
- **Human Resources:** *[TBD - If project affects staff, training, or organizational change]*

### External Stakeholders
*[Instruction: Consider the following external stakeholder categories based on project scope:]*

- **Vendors/Suppliers:** *[TBD - Technology providers, service contractors]*
- **Regulatory Bodies:** *[TBD - If applicable to industry/project type]*
- **End Customers:** *[TBD - If project affects customer-facing services]*

---

## 4. Stakeholder Analysis Matrix

### Power/Interest Grid

*[AI Instruction: Categorize all identified stakeholders into the power/interest matrix based on their roles and project impact.]*

| High Power, High Interest | High Power, Low Interest |
|:---|:---|
| *[Manage Closely - Key Decision Makers]* | *[Keep Satisfied - Executives/Sponsors]* |
| *[List stakeholders from analysis above]* | *[List stakeholders requiring updates]* |

| Low Power, High Interest | Low Power, Low Interest |
|:---|:---|
| *[Keep Informed - End Users/Champions]* | *[Monitor - Peripheral Stakeholders]* |
| *[List engaged users and advocates]* | *[List for awareness only]* |

---

## 5. Stakeholder Requirements and Expectations

### Communication Preferences
*[AI Instruction: Extract communication preferences from User Personas where available, and provide standard templates for organizational stakeholders.]*

| Stakeholder | Preferred Communication Method | Frequency | Key Information Needs |
|:---|:---|:---|:---|
| *[From User Personas]* | *[Extract from Persona]* | *[Extract/Infer from Persona]* | *[Extract from Goals/Pain Points]* |

---

## 6. Data Sources and Completion Instructions

### To Complete This Register:

1. **Review Generated Stakeholder Analysis:** Validate the stakeholders extracted from User Personas and User Stories
2. **Consult Organizational Assets:**
   - Organization charts and reporting structures
   - Entra ID/Active Directory for department structures
   - Previous project stakeholder registers
   - Governance documentation
3. **Conduct Stakeholder Interviews:** Validate requirements and engagement preferences
4. **Update Contact Information:** Add specific contact details from organizational directory

### Recommended Next Steps:
1. **Stakeholder Analysis Workshop:** Review this register with project team
2. **Stakeholder Interviews:** Conduct one-on-one meetings with high-power stakeholders  
3. **Engagement Plan Development:** Use this register to develop the Stakeholder Engagement Plan
4. **Regular Updates:** Update this register throughout project lifecycle as stakeholders change

---

*This document was intelligently pre-populated by analyzing User Personas and project context. Please review, validate, and complete the organizational sections to ensure comprehensive stakeholder coverage.*`;
  }
}
