import type { ProjectContext } from '../../ai/types';

/**
 * Stakeholder Needs Analysis Template
 * 
 * Provides the structure and framework for analyzing stakeholder and sponsor needs
 * to ensure clear project charters and effective engagement plans.
 */
export class StakeholderNeedsAnalysisTemplate {
  constructor(private context: ProjectContext) {}

  /**
   * Generate the template structure for stakeholder needs analysis
   */
  generateContent(): string {
    const projectName = this.context.projectName || 'Project';
    const projectType = this.context.projectType || 'Strategic Initiative';
    
    return `# Stakeholder Needs Analysis

**Generated by Requirements Gathering Agent v2.1.3**  
**Category:** stakeholder-management  
**Generated:** ${new Date().toISOString()}  
**Description:** Comprehensive analysis of stakeholder and sponsor needs for clear project charters and engagement plans

---

## 🎯 **ANALYSIS OBJECTIVES**

**MISSION**: Analyze stakeholder and sponsor needs to ensure the Requirements Gathering Agent provides clear, actionable project charters and effective engagement plans that drive successful project authorization and stakeholder participation.

**FOCUS AREAS**:
1. **Sponsor Authorization Requirements** → What sponsors need to authorize projects confidently
2. **Stakeholder Information Needs** → Information requirements by stakeholder type and project phase
3. **Charter Clarity Factors** → Elements that make project charters clear and actionable
4. **Engagement Plan Effectiveness** → Strategies that drive successful stakeholder participation
5. **Communication Optimization** → Tailored communication approaches by stakeholder group

---

# Stakeholder Needs Analysis - ${projectName}

**Project Title:** ${projectName}  
**Project Type:** ${projectType}  
**Analysis Date:** ${new Date().toISOString().split('T')[0]}  
**Analyst:** [BUSINESS ANALYST NAME]  
**Stakeholder Management Lead:** [STAKEHOLDER LEAD NAME]

---

## Executive Summary

**Analysis Purpose:**  
[AI_SYNTHESIS: Explain the purpose of analyzing stakeholder needs for this specific project and how it will improve charter clarity and engagement effectiveness]

**Key Stakeholder Insights:**  
[AI_SYNTHESIS: Summarize the most critical findings about stakeholder needs, expectations, and requirements for project success]

**Charter and Engagement Recommendations:**  
[AI_SYNTHESIS: Provide high-level recommendations for improving project charter clarity and stakeholder engagement plan effectiveness]

---

## 1. Sponsor Authorization Needs Assessment

### Executive Sponsor Profile
**Decision-Making Context:**  
[AI_SYNTHESIS: Analyze the executive sponsor's decision-making context, including organizational pressures, strategic priorities, and risk tolerance]

**Authorization Criteria:**  
[AI_SYNTHESIS: Define the specific criteria sponsors use to evaluate and authorize projects, including strategic alignment, resource requirements, and success probability]

### Charter Requirements for Sponsor Confidence
**Strategic Justification Needs:**
- **Business Case Clarity:** [AI_SYNTHESIS: Define what sponsors need to see in business justification to authorize confidently]
- **ROI Presentation:** [AI_SYNTHESIS: Specify how ROI should be presented for sponsor understanding and confidence]
- **Strategic Alignment Evidence:** [AI_SYNTHESIS: Identify how sponsors evaluate strategic fit with organizational objectives]

**Risk and Resource Assessment:**
- **Risk Transparency Requirements:** [AI_SYNTHESIS: Define sponsor needs for risk visibility and mitigation confidence]
- **Resource Authorization Clarity:** [AI_SYNTHESIS: Specify what sponsors need to commit organizational resources]
- **Success Metrics Definition:** [AI_SYNTHESIS: Identify sponsor requirements for measurable success criteria]

**Decision Support Information:**
- **Information Depth and Breadth:** [AI_SYNTHESIS: Analyze the level of detail sponsors require for confident decision-making]
- **Timeline Confidence Factors:** [AI_SYNTHESIS: Define what sponsors need to believe in project timelines and milestones]
- **Stakeholder Support Evidence:** [AI_SYNTHESIS: Identify how sponsors assess stakeholder buy-in and support]

---

## 2. Stakeholder Information Needs by Category

### High-Power, High-Interest Stakeholders

#### Executive Leadership
**Information Requirements:**
- **Strategic Context:** [AI_SYNTHESIS: Define executive-level strategic information needs]
- **Progress Indicators:** [AI_SYNTHESIS: Specify progress reporting requirements for executives]
- **Escalation Triggers:** [AI_SYNTHESIS: Identify when executives need to be engaged or consulted]

**Communication Preferences:**
- **Format:** [AI_SYNTHESIS: Define preferred communication formats for executive stakeholders]
- **Frequency:** [AI_SYNTHESIS: Specify optimal communication frequency for executive engagement]
- **Channel:** [AI_SYNTHESIS: Identify preferred communication channels and methods]

#### Project Sponsors
**Authorization Information Needs:**
- **Project Justification:** [AI_SYNTHESIS: Define information needed for initial project authorization]
- **Resource Commitments:** [AI_SYNTHESIS: Specify resource authorization information requirements]
- **Success Criteria:** [AI_SYNTHESIS: Identify success measurement information needs]

**Ongoing Oversight Requirements:**
- **Progress Monitoring:** [AI_SYNTHESIS: Define ongoing information needs for project oversight]
- **Risk Management:** [AI_SYNTHESIS: Specify risk monitoring and escalation information needs]
- **Stakeholder Feedback:** [AI_SYNTHESIS: Identify stakeholder satisfaction and engagement information needs]

### High-Interest, Variable-Power Stakeholders

#### End Users and Beneficiaries
**Engagement Information Needs:**
- **Project Impact:** [AI_SYNTHESIS: Define what end users need to understand about project impact on their work]
- **Participation Opportunities:** [AI_SYNTHESIS: Specify how end users can participate in and influence the project]
- **Training and Support:** [AI_SYNTHESIS: Identify information needs for user adoption and support]

**Feedback and Input Requirements:**
- **Feedback Mechanisms:** [AI_SYNTHESIS: Define how end users should provide input and feedback]
- **Requirement Validation:** [AI_SYNTHESIS: Specify how end users can validate requirements and solutions]
- **Change Management:** [AI_SYNTHESIS: Identify change management information and support needs]

#### Subject Matter Experts (SMEs)
**Technical Engagement Needs:**
- **Expertise Requirements:** [AI_SYNTHESIS: Define what SMEs need to understand about their role and contributions]
- **Technical Specifications:** [AI_SYNTHESIS: Specify technical information needs for SME participation]
- **Validation Processes:** [AI_SYNTHESIS: Identify how SMEs should validate technical requirements and solutions]

**Knowledge Transfer Requirements:**
- **Documentation Needs:** [AI_SYNTHESIS: Define documentation requirements for SME knowledge transfer]
- **Training and Mentoring:** [AI_SYNTHESIS: Specify SME roles in training and knowledge sharing]
- **Ongoing Support:** [AI_SYNTHESIS: Identify ongoing SME support and consultation needs]

### Regulatory and Compliance Stakeholders

#### Compliance Officers
**Regulatory Information Needs:**
- **Compliance Requirements:** [AI_SYNTHESIS: Define compliance information needs and regulatory considerations]
- **Audit Trail Requirements:** [AI_SYNTHESIS: Specify documentation needs for compliance and audit purposes]
- **Risk Management:** [AI_SYNTHESIS: Identify compliance risk management information needs]

**Oversight and Validation:**
- **Review Processes:** [AI_SYNTHESIS: Define compliance review and validation process requirements]
- **Reporting Requirements:** [AI_SYNTHESIS: Specify compliance reporting and documentation needs]
- **Escalation Procedures:** [AI_SYNTHESIS: Identify compliance escalation and issue resolution procedures]

---

## 3. Charter Clarity Enhancement Requirements

### Essential Charter Components for Stakeholder Confidence

#### Strategic Context Presentation
**Business Justification:**
- **Strategic Alignment:** [AI_SYNTHESIS: Define how strategic alignment should be presented in charters]
- **Value Proposition:** [AI_SYNTHESIS: Specify value proposition presentation requirements]
- **Organizational Impact:** [AI_SYNTHESIS: Identify organizational impact presentation needs]

**Resource and Timeline Clarity:**
- **Resource Authorization:** [AI_SYNTHESIS: Define resource commitment presentation requirements]
- **Timeline Confidence:** [AI_SYNTHESIS: Specify timeline presentation for stakeholder confidence]
- **Milestone Definition:** [AI_SYNTHESIS: Identify milestone presentation and tracking requirements]

#### Risk and Success Criteria
**Risk Communication:**
- **Risk Transparency:** [AI_SYNTHESIS: Define risk presentation requirements for stakeholder confidence]
- **Mitigation Strategies:** [AI_SYNTHESIS: Specify mitigation strategy presentation needs]
- **Contingency Planning:** [AI_SYNTHESIS: Identify contingency planning presentation requirements]

**Success Metrics:**
- **Measurable Outcomes:** [AI_SYNTHESIS: Define success criteria presentation requirements]
- **Stakeholder Value:** [AI_SYNTHESIS: Specify stakeholder value demonstration needs]
- **Progress Tracking:** [AI_SYNTHESIS: Identify progress tracking and reporting requirements]

### Charter Quality Indicators
**Clarity Metrics:**
- **Information Completeness:** [AI_SYNTHESIS: Define charter completeness assessment criteria]
- **Stakeholder Understanding:** [AI_SYNTHESIS: Specify stakeholder comprehension assessment methods]
- **Action Orientation:** [AI_SYNTHESIS: Identify actionability assessment requirements]

**Confidence Factors:**
- **Sponsor Confidence:** [AI_SYNTHESIS: Define sponsor confidence assessment criteria]
- **Stakeholder Buy-in:** [AI_SYNTHESIS: Specify stakeholder support assessment methods]
- **Authorization Readiness:** [AI_SYNTHESIS: Identify authorization readiness assessment requirements]

---

## 4. Engagement Plan Effectiveness Analysis

### Stakeholder-Specific Engagement Strategies

#### High-Power Stakeholder Engagement
**Influence and Authority Management:**
- **Engagement Frequency:** [AI_SYNTHESIS: Define optimal engagement frequency for high-power stakeholders]
- **Decision Involvement:** [AI_SYNTHESIS: Specify decision involvement and consultation requirements]
- **Escalation Management:** [AI_SYNTHESIS: Identify escalation and issue resolution procedures]

**Communication and Reporting:**
- **Information Depth:** [AI_SYNTHESIS: Define information depth requirements for high-power stakeholders]
- **Reporting Frequency:** [AI_SYNTHESIS: Specify reporting frequency and format requirements]
- **Feedback Integration:** [AI_SYNTHESIS: Identify feedback integration and response procedures]

#### High-Interest Stakeholder Engagement
**Participation and Involvement:**
- **Meaningful Participation:** [AI_SYNTHESIS: Define meaningful participation opportunities for high-interest stakeholders]
- **Input and Feedback:** [AI_SYNTHESIS: Specify input and feedback collection and integration methods]
- **Recognition and Motivation:** [AI_SYNTHESIS: Identify recognition and motivation strategies for sustained engagement]

**Communication and Support:**
- **Information Sharing:** [AI_SYNTHESIS: Define information sharing requirements for high-interest stakeholders]
- **Training and Support:** [AI_SYNTHESIS: Specify training and support provision requirements]
- **Change Management:** [AI_SYNTHESIS: Identify change management and adoption support needs]

### Communication Effectiveness Factors
**Message Optimization:**
- **Audience-Appropriate Language:** [AI_SYNTHESIS: Define communication style requirements by stakeholder type]
- **Information Hierarchy:** [AI_SYNTHESIS: Specify information prioritization and presentation methods]
- **Action Orientation:** [AI_SYNTHESIS: Identify action-oriented communication requirements]

**Channel and Timing Optimization:**
- **Channel Selection:** [AI_SYNTHESIS: Define communication channel selection criteria by stakeholder type]
- **Timing Optimization:** [AI_SYNTHESIS: Specify optimal communication timing and frequency]
- **Multi-Channel Strategies:** [AI_SYNTHESIS: Identify multi-channel communication strategy requirements]

---

## 5. Requirements Gathering Agent Enhancement Recommendations

### Immediate Charter Generation Improvements
**Sponsor-Focused Enhancements:**
1. **Strategic Context Synthesis:** [AI_SYNTHESIS: Recommend improvements to strategic context presentation in charters]
2. **Resource Authorization Clarity:** [AI_SYNTHESIS: Suggest enhancements to resource commitment presentation]
3. **Risk Communication Enhancement:** [AI_SYNTHESIS: Recommend improvements to risk presentation and mitigation strategies]

**Stakeholder-Specific Charter Views:**
1. **Executive Summary Optimization:** [AI_SYNTHESIS: Suggest executive summary enhancements for different stakeholder types]
2. **Technical Detail Layering:** [AI_SYNTHESIS: Recommend technical detail presentation strategies]
3. **Action Item Clarity:** [AI_SYNTHESIS: Suggest action item and next steps presentation improvements]

### Engagement Plan Generation Improvements
**Content Enhancement:**
1. **Stakeholder-Specific Strategies:** [AI_SYNTHESIS: Recommend tailored engagement approach development]
2. **Communication Calendar Integration:** [AI_SYNTHESIS: Suggest automated communication scheduling and tracking]
3. **Feedback Loop Automation:** [AI_SYNTHESIS: Recommend automated feedback collection and integration systems]

**Process Optimization:**
1. **Needs Assessment Automation:** [AI_SYNTHESIS: Suggest automated stakeholder needs analysis capabilities]
2. **Engagement Effectiveness Monitoring:** [AI_SYNTHESIS: Recommend automated engagement tracking and assessment]
3. **Adaptive Strategy Development:** [AI_SYNTHESIS: Suggest dynamic engagement plan adjustment capabilities]

### Advanced Stakeholder Intelligence Capabilities
**Predictive Analytics:**
1. **Stakeholder Behavior Prediction:** [AI_SYNTHESIS: Recommend stakeholder behavior prediction capabilities]
2. **Engagement Success Forecasting:** [AI_SYNTHESIS: Suggest engagement success prediction and optimization]
3. **Risk Early Warning Systems:** [AI_SYNTHESIS: Recommend stakeholder risk early warning capabilities]

**Intelligent Automation:**
1. **Dynamic Content Generation:** [AI_SYNTHESIS: Suggest dynamic content generation based on stakeholder profiles]
2. **Automated Stakeholder Matching:** [AI_SYNTHESIS: Recommend automated stakeholder-strategy matching]
3. **Continuous Improvement Learning:** [AI_SYNTHESIS: Suggest machine learning for continuous stakeholder management improvement]

---

## 6. Implementation Roadmap and Success Metrics

### Phase 1: Charter Clarity Enhancement (0-3 months)
**Objectives:** [AI_SYNTHESIS: Define specific objectives for charter clarity improvement]
**Key Activities:** [AI_SYNTHESIS: List specific implementation activities and milestones]
**Success Criteria:** [AI_SYNTHESIS: Define measurable success criteria and assessment methods]

### Phase 2: Engagement Plan Optimization (3-6 months)
**Objectives:** [AI_SYNTHESIS: Define specific objectives for engagement plan improvement]
**Key Activities:** [AI_SYNTHESIS: List specific implementation activities and milestones]
**Success Criteria:** [AI_SYNTHESIS: Define measurable success criteria and assessment methods]

### Phase 3: Advanced Intelligence Integration (6-12 months)
**Objectives:** [AI_SYNTHESIS: Define specific objectives for advanced stakeholder intelligence]
**Key Activities:** [AI_SYNTHESIS: List specific implementation activities and milestones]
**Success Criteria:** [AI_SYNTHESIS: Define measurable success criteria and assessment methods]

### Success Metrics and Monitoring
**Charter Quality Metrics:**
- **Sponsor Authorization Rate:** [AI_SYNTHESIS: Define target authorization success rates and measurement methods]
- **Charter Revision Frequency:** [AI_SYNTHESIS: Specify acceptable revision rates and quality indicators]
- **Stakeholder Confidence Scores:** [AI_SYNTHESIS: Define confidence measurement and assessment methods]

**Engagement Effectiveness Metrics:**
- **Participation Rates:** [AI_SYNTHESIS: Define target participation levels by stakeholder group]
- **Satisfaction Scores:** [AI_SYNTHESIS: Specify satisfaction measurement and assessment methods]
- **Communication Effectiveness:** [AI_SYNTHESIS: Define communication success indicators and metrics]

**System Performance Metrics:**
- **Document Quality Scores:** [AI_SYNTHESIS: Define quality assessment methods and criteria]
- **Process Efficiency Gains:** [AI_SYNTHESIS: Specify efficiency improvement measurements and targets]
- **Stakeholder Feedback Integration:** [AI_SYNTHESIS: Define feedback incorporation metrics and success indicators]

---

## Conclusion and Next Steps

**Analysis Summary:**  
[AI_SYNTHESIS: Summarize the key findings and recommendations from the stakeholder needs analysis]

**Critical Success Factors:**  
[AI_SYNTHESIS: Identify the most critical factors for successful implementation of recommendations]

**Immediate Actions Required:**  
[AI_SYNTHESIS: Define immediate actions needed to begin implementation of recommendations]

**Long-term Vision:**  
[AI_SYNTHESIS: Describe the long-term vision for stakeholder management excellence within the Requirements Gathering Agent]

---

*This Stakeholder Needs Analysis provides a comprehensive framework for understanding and addressing stakeholder and sponsor needs to ensure the Requirements Gathering Agent delivers clear project charters and effective engagement plans that drive project success.*`;
  }
}

