// DataQualityManagementPlanTemplate.ts
import type { ProjectContext } from '../../ai/types.js';

/**
 * Generates the content for the Data Quality Management Plan document.
 * @param context Project context and relationships
 * @returns Markdown string for the Data Quality Management Plan
 */
export function generateContent(context: ProjectContext): string {
  return `# Data Quality Management Plan

## 1. Introduction
Describe the purpose, scope, and objectives of data quality management for this project.

## 2. Data Quality Objectives and Metrics
- Define measurable data quality goals
- List key metrics and thresholds

## 3. Roles and Responsibilities
- Data quality manager
- Data stewards
- Stakeholders

## 4. Data Quality Assessment and Monitoring
- Assessment methods
- Monitoring frequency
- Reporting structure

## 5. Data Cleansing and Remediation
- Procedures for identifying and correcting data issues
- Escalation and remediation workflow

## 6. Compliance, Risk, and Audit
- Regulatory requirements
- Risk management
- Audit processes

## 7. Communication and Training
- Communication plan for data quality
- Training and awareness programs

## 8. Continuous Improvement
- Feedback mechanisms
- Review and update schedule

---
*This document was generated by the Requirements Gathering Agent.*
`;
}
