import type { ProjectContext } from '../../ai/types';

/**
 * @description A template for generating a Benefits Realization Plan document.
 * It provides a structured format for defining, tracking, and measuring
 * project benefits according to PMBOK standards and best practices.
 */
export class BenefitsRealizationPlanTemplate {
  constructor(private context: ProjectContext) {}

  /**
   * Build the markdown content for Benefits Realization Plan
   */
  generateContent(): string {
    const currentDate = new Date().toISOString();
    
    return `# Benefits Realization Plan: ${this.context.projectName}

**Generated by:** ADPA (Automated Documentation Project Assistant)
**Category:** strategic-planning
**Generated:** ${currentDate}
**Version:** 1.0
**PMBOK Process Group:** Initiating & Monitoring/Controlling
**PMBOK Knowledge Area:** Project Benefits Management

---

## 1. Executive Summary

*[Instruction: Provide a concise overview of the expected benefits from this project. State the primary value proposition, key benefit categories, and expected timeline for benefit realization. This should clearly articulate why the investment is worthwhile.]*

---

## 2. Benefits Overview

### 2.1 Benefits Definition
*[Instruction: Define what constitutes a "benefit" for this project. Explain the difference between outputs, outcomes, and benefits in the context of this project.]*

### 2.2 Benefits Categories
*[Instruction: Categorize the expected benefits (e.g., financial, operational, strategic, compliance, customer satisfaction).]*

| Benefit Category | Description | Expected Value |
| :--- | :--- | :--- |
| **Financial Benefits** | *[Direct cost savings, revenue increases]* | *[Quantified value]* |
| **Operational Benefits** | *[Efficiency gains, process improvements]* | *[Quantified value]* |
| **Strategic Benefits** | *[Competitive advantage, market position]* | *[Qualitative description]* |
| **Risk Benefits** | *[Risk reduction, compliance improvements]* | *[Risk mitigation value]* |

---

## 3. Detailed Benefits Analysis

### 3.1 Primary Benefits

#### Benefit 1: [Primary Benefit Name]
- **Description:** *[Detailed description of the benefit]*
- **Type:** *[Financial/Operational/Strategic/Risk]*
- **Quantification:** *[How the benefit will be measured and valued]*
- **Baseline:** *[Current state measurement]*
- **Target:** *[Expected future state]*
- **Realization Timeline:** *[When the benefit will be realized]*
- **Dependencies:** *[What must happen for this benefit to be realized]*

#### Benefit 2: [Secondary Benefit Name]
- **Description:** *[Detailed description of the benefit]*
- **Type:** *[Financial/Operational/Strategic/Risk]*
- **Quantification:** *[How the benefit will be measured and valued]*
- **Baseline:** *[Current state measurement]*
- **Target:** *[Expected future state]*
- **Realization Timeline:** *[When the benefit will be realized]*
- **Dependencies:** *[What must happen for this benefit to be realized]*

#### Benefit 3: [Additional Benefit Name]
- **Description:** *[Detailed description of the benefit]*
- **Type:** *[Financial/Operational/Strategic/Risk]*
- **Quantification:** *[How the benefit will be measured and valued]*
- **Baseline:** *[Current state measurement]*
- **Target:** *[Expected future state]*
- **Realization Timeline:** *[When the benefit will be realized]*
- **Dependencies:** *[What must happen for this benefit to be realized]*

### 3.2 Secondary Benefits
*[Instruction: List additional benefits that may be realized but are not primary drivers for the project.]*

---

## 4. Benefits Measurement Framework

### 4.1 Key Performance Indicators (KPIs)
*[Instruction: Define specific, measurable KPIs for tracking benefit realization.]*

| KPI | Measurement Method | Baseline Value | Target Value | Measurement Frequency |
| :--- | :--- | :--- | :--- | :--- |
| *[KPI 1]* | *[How measured]* | *[Current value]* | *[Target value]* | *[How often measured]* |
| *[KPI 2]* | *[How measured]* | *[Current value]* | *[Target value]* | *[How often measured]* |
| *[KPI 3]* | *[How measured]* | *[Current value]* | *[Target value]* | *[How often measured]* |

### 4.2 Measurement Tools & Systems
*[Instruction: Describe the tools, systems, and processes that will be used to measure and track benefits.]*

### 4.3 Data Collection Plan
*[Instruction: Outline how data will be collected, who is responsible, and how often.]*

| Data Element | Collection Method | Responsible Party | Collection Frequency |
| :--- | :--- | :--- | :--- |
| *[Data 1]* | *[Method]* | *[Person/Role]* | *[Frequency]* |
| *[Data 2]* | *[Method]* | *[Person/Role]* | *[Frequency]* |

---

## 5. Benefits Realization Timeline

### 5.1 Benefits Roadmap
*[Instruction: Create a timeline showing when different benefits are expected to be realized.]*

| Timeline | Milestone | Expected Benefits | Measurement Activities |
| :--- | :--- | :--- | :--- |
| **Month 1-3** | *[Early milestone]* | *[Early benefits]* | *[Initial measurements]* |
| **Month 4-6** | *[Mid-term milestone]* | *[Developing benefits]* | *[Progress measurements]* |
| **Month 7-12** | *[Long-term milestone]* | *[Full benefits]* | *[Full measurement]* |
| **Year 2+** | *[Sustained benefits]* | *[Ongoing benefits]* | *[Continuous monitoring]* |

### 5.2 Critical Success Factors
*[Instruction: Identify the factors that are critical for successful benefit realization.]*

1. **[Factor 1]:** *[Description and importance]*
2. **[Factor 2]:** *[Description and importance]*
3. **[Factor 3]:** *[Description and importance]*

---

## 6. Stakeholder Benefits Analysis

### 6.1 Stakeholder Benefit Mapping
*[Instruction: Map specific benefits to different stakeholder groups.]*

| Stakeholder Group | Primary Benefits | Secondary Benefits | Benefit Realization Role |
| :--- | :--- | :--- | :--- |
| *[Stakeholder 1]* | *[Main benefits for them]* | *[Additional benefits]* | *[Their role in realization]* |
| *[Stakeholder 2]* | *[Main benefits for them]* | *[Additional benefits]* | *[Their role in realization]* |
| *[Stakeholder 3]* | *[Main benefits for them]* | *[Additional benefits]* | *[Their role in realization]* |

### 6.2 Stakeholder Engagement for Benefits
*[Instruction: Describe how stakeholders will be engaged in the benefits realization process.]*

---

## 7. Benefits Realization Governance

### 7.1 Roles & Responsibilities
*[Instruction: Define who is responsible for different aspects of benefits realization.]*

| Role | Responsibilities | Accountabilities |
| :--- | :--- | :--- |
| **Benefits Owner** | *[Primary responsibilities]* | *[What they're accountable for]* |
| **Project Manager** | *[PM responsibilities]* | *[PM accountabilities]* |
| **Business Sponsor** | *[Sponsor responsibilities]* | *[Sponsor accountabilities]* |
| **Benefits Analyst** | *[Analyst responsibilities]* | *[Analyst accountabilities]* |

### 7.2 Benefits Review Process
*[Instruction: Define the process for regularly reviewing and validating benefit realization.]*

### 7.3 Benefits Reporting
*[Instruction: Outline how benefits progress will be reported and to whom.]*

| Report Type | Audience | Frequency | Content Focus |
| :--- | :--- | :--- | :--- |
| **Executive Dashboard** | *[Senior leadership]* | *[Monthly/Quarterly]* | *[High-level metrics]* |
| **Detailed Benefits Report** | *[Project stakeholders]* | *[Monthly]* | *[Detailed progress]* |
| **Benefits Realization Review** | *[Steering committee]* | *[Quarterly]* | *[Comprehensive review]* |

---

## 8. Risk Management for Benefits

### 8.1 Benefits Realization Risks
*[Instruction: Identify risks that could prevent or reduce benefit realization.]*

| Risk | Impact on Benefits | Probability | Mitigation Strategy |
| :--- | :--- | :--- | :--- |
| *[Risk 1]* | *[How it affects benefits]* | *[High/Med/Low]* | *[Mitigation approach]* |
| *[Risk 2]* | *[How it affects benefits]* | *[High/Med/Low]* | *[Mitigation approach]* |
| *[Risk 3]* | *[How it affects benefits]* | *[High/Med/Low]* | *[Mitigation approach]* |

### 8.2 Contingency Planning
*[Instruction: Describe contingency plans if expected benefits are not realized.]*

---

## 9. Benefits Optimization

### 9.1 Benefit Enhancement Opportunities
*[Instruction: Identify opportunities to enhance or accelerate benefit realization.]*

### 9.2 Continuous Improvement
*[Instruction: Describe how the benefits realization process will be continuously improved.]*

---

## 10. Post-Project Benefits Sustainability

### 10.1 Sustainability Plan
*[Instruction: Describe how benefits will be sustained after project completion.]*

### 10.2 Transition to Operations
*[Instruction: Outline how benefit tracking and management will transition to operational teams.]*

### 10.3 Long-term Monitoring
*[Instruction: Define long-term monitoring and evaluation of benefits.]*

---

## 11. Financial Analysis

### 11.1 Cost-Benefit Analysis
*[Instruction: Provide detailed cost-benefit analysis including ROI calculations.]*

| Financial Metric | Value | Calculation Method | Assumptions |
| :--- | :--- | :--- | :--- |
| **Total Investment** | *[Amount]* | *[How calculated]* | *[Key assumptions]* |
| **Total Benefits (3 years)** | *[Amount]* | *[How calculated]* | *[Key assumptions]* |
| **Net Present Value (NPV)** | *[Amount]* | *[Discount rate and method]* | *[Key assumptions]* |
| **Return on Investment (ROI)** | *[Percentage]* | *[Calculation method]* | *[Key assumptions]* |
| **Payback Period** | *[Time period]* | *[Calculation method]* | *[Key assumptions]* |

### 11.2 Sensitivity Analysis
*[Instruction: Analyze how changes in key assumptions affect the financial benefits.]*

---

## 12. Conclusion & Next Steps

*[Instruction: Summarize the benefits realization approach and outline immediate next steps for implementation.]*

**Benefits Realization Commitment:** This plan establishes a comprehensive framework for realizing and measuring the expected benefits from ${this.context.projectName}, ensuring maximum value delivery to the organization.

---

**Document Approval:**
- **Benefits Owner:** *[Name and signature line]*
- **Project Sponsor:** *[Name and signature line]*
- **Finance Representative:** *[Name and signature line]*
- **Date:** *[Approval date]*
`;
  }
}