import type { ProjectContext } from '../../ai/types';

/**
 * Company Values Template - A structured format for generating formal Company Values documents.
 * This template provides instructional guidance for the AI to create professional, actionable core values.
 */
export class CompanyValuesTemplate {
  constructor(private context: ProjectContext) {}

  /**
   * Generate the instructional template for Company Values document
   */
  generateContent(): string {
    return `# ${this.context.projectName || '[Company Name]'} - Our Core Values

**Generated by:** ADPA (Automated Documentation Project Assistant)  
**Category:** strategic-statements  
**Generated:** ${new Date().toLocaleDateString()}  
**Description:** This document outlines the core values that guide our decisions, actions, and culture.

---

## 1. Our Guiding Principles

*[Instruction: Write a brief, inspiring introduction about the importance of these values to the company's mission, culture, and long-term success. Explain how these principles are the foundation of how the team works together and serves its customers. Base this on the project context provided.]*

**Template Example:** "At [Company Name], our core values are not just words on a wall—they are the driving force behind every decision we make and every relationship we build. These principles guide how we innovate, collaborate, and deliver value to our customers and stakeholders."

---

## 2. The Values We Live By

### **Value 1: [Name of the Value]**

*   **Definition:** *[Instruction: Provide a concise, one-sentence definition of this value in the context of this specific company/project.]*
*   **Why It Matters:** *[Instruction: Describe why this value is crucial for success, culture, and customer relationships. Connect it to a business objective if possible.]*
*   **In Action (Behavioral Examples):**
    *   *[Instruction: List 2-3 specific, actionable behaviors that demonstrate this value in day-to-day work. Focus on tangible actions, not abstract ideas.]*
    *   *[Example Behavior 2 - be specific and measurable]*
    *   *[Example Behavior 3 - connect to actual work scenarios]*

---

### **Value 2: [Name of the Value]**

*   **Definition:** *[Instruction: Provide a concise, one-sentence definition of this value in the context of this specific company/project.]*
*   **Why It Matters:** *[Instruction: Describe why this value is crucial for success, culture, and customer relationships. Connect it to a business objective if possible.]*
*   **In Action (Behavioral Examples):**
    *   *[Instruction: List 2-3 specific, actionable behaviors that demonstrate this value in day-to-day work. Focus on tangible actions, not abstract ideas.]*
    *   *[Example Behavior 2 - be specific and measurable]*
    *   *[Example Behavior 3 - connect to actual work scenarios]*

---

### **Value 3: [Name of the Value]**

*   **Definition:** *[Instruction: Provide a concise, one-sentence definition of this value in the context of this specific company/project.]*
*   **Why It Matters:** *[Instruction: Describe why this value is crucial for success, culture, and customer relationships. Connect it to a business objective if possible.]*
*   **In Action (Behavioral Examples):**
    *   *[Instruction: List 2-3 specific, actionable behaviors that demonstrate this value in day-to-day work. Focus on tangible actions, not abstract ideas.]*
    *   *[Example Behavior 2 - be specific and measurable]*
    *   *[Example Behavior 3 - connect to actual work scenarios]*

---

*[Instruction: Add additional value sections (4-5 total) based on the provided context. Ensure each value is distinct and covers different aspects of organizational culture and business success.]*

## 3. Living Our Values

### **Hiring & Team Building**
*[Instruction: Explain how these values guide recruitment, onboarding, and team development.]*

### **Decision Making**
*[Instruction: Describe how teams should use these values when making difficult choices or trade-offs.]*

### **Performance & Recognition**
*[Instruction: Connect values to performance evaluation and recognition programs.]*

## 4. Our Commitment

*[Instruction: Write a powerful concluding paragraph that reinforces the company's commitment to upholding these values in all aspects of the business, from hiring and promotions to product development and customer support. Make it inspiring and actionable.]*

---

**Document Version:** 1.0  
**Last Updated:** ${new Date().toLocaleDateString()}  
**Next Review:** ${new Date(Date.now() + 180 * 24 * 60 * 60 * 1000).toLocaleDateString()}`;
  }
}
