import type { ProjectContext } from '../../ai/types';

/**
 * @description A template for generating a Strategic Alignment document.
 * It provides a structured format for demonstrating how the project aligns
 * with organizational strategy, goals, and objectives according to PMBOK standards.
 */
export class StrategicAlignmentTemplate {
  constructor(private context: ProjectContext) {}

  /**
   * Build the markdown content for Strategic Alignment
   */
  generateContent(): string {
    const currentDate = new Date().toISOString();
    
    return `# Strategic Alignment Document: ${this.context.projectName}

**Generated by:** ADPA (Automated Documentation Project Assistant)
**Category:** strategic-planning
**Generated:** ${currentDate}
**Version:** 1.0
**PMBOK Process Group:** Initiating
**PMBOK Knowledge Area:** Project Integration Management

---

## 1. Executive Summary

*[Instruction: Provide a concise overview of how this project aligns with organizational strategy. State the strategic imperative, key alignment points, and expected strategic contribution. This should demonstrate clear line of sight from project outcomes to strategic objectives.]*

---

## 2. Organizational Strategic Context

### 2.1 Strategic Vision & Mission Alignment
*[Instruction: Describe how the project supports the organization's vision and mission. Reference specific elements of the organizational mission/vision that this project advances.]*

### 2.2 Strategic Goals & Objectives
*[Instruction: List the specific organizational strategic goals that this project supports. For each goal, explain the connection and expected contribution.]*

| Strategic Goal | Project Contribution | Expected Impact |
| :--- | :--- | :--- |
| *[Goal 1]* | *[How project supports this goal]* | *[Measurable impact]* |
| *[Goal 2]* | *[How project supports this goal]* | *[Measurable impact]* |
| *[Goal 3]* | *[How project supports this goal]* | *[Measurable impact]* |

---

## 3. Strategic Drivers & Business Case Alignment

### 3.1 Primary Strategic Drivers
*[Instruction: Identify the key strategic drivers that necessitate this project (e.g., market pressures, regulatory requirements, competitive positioning, operational efficiency).]*

1. **[Driver 1]:** *[Description and relevance]*
2. **[Driver 2]:** *[Description and relevance]*
3. **[Driver 3]:** *[Description and relevance]*

### 3.2 Strategic Priorities Addressed
*[Instruction: Map the project to current organizational strategic priorities. Show how the project advances these priorities.]*

---

## 4. Portfolio & Program Alignment

### 4.1 Portfolio Strategic Fit
*[Instruction: Explain how this project fits within the organization's project portfolio. Describe synergies with other strategic initiatives.]*

### 4.2 Program Dependencies
*[Instruction: Identify any program-level dependencies or relationships that support strategic objectives.]*

### 4.3 Resource Allocation Justification
*[Instruction: Justify the strategic importance of allocating resources to this project versus other potential investments.]*

---

## 5. Stakeholder Strategic Interests

### 5.1 Executive Stakeholder Alignment
*[Instruction: Describe how the project serves the strategic interests of key executive stakeholders.]*

| Stakeholder | Strategic Interest | Project Alignment |
| :--- | :--- | :--- |
| *[Executive 1]* | *[Their strategic focus]* | *[How project serves their interests]* |
| *[Executive 2]* | *[Their strategic focus]* | *[How project serves their interests]* |

### 5.2 Business Unit Strategic Benefits
*[Instruction: Outline the strategic benefits for different business units or departments.]*

---

## 6. Strategic Success Criteria

### 6.1 Strategic Outcomes
*[Instruction: Define the strategic outcomes that will indicate successful alignment and contribution to organizational strategy.]*

1. **[Outcome 1]:** *[Description and measurement approach]*
2. **[Outcome 2]:** *[Description and measurement approach]*
3. **[Outcome 3]:** *[Description and measurement approach]*

### 6.2 Strategic KPIs
*[Instruction: Identify key performance indicators that measure strategic contribution.]*

| KPI | Target | Measurement Method | Review Frequency |
| :--- | :--- | :--- | :--- |
| *[KPI 1]* | *[Target value]* | *[How measured]* | *[When reviewed]* |
| *[KPI 2]* | *[Target value]* | *[How measured]* | *[When reviewed]* |

---

## 7. Strategic Risk Assessment

### 7.1 Strategic Risks
*[Instruction: Identify risks that could impact strategic alignment or contribution.]*

| Risk | Impact on Strategy | Mitigation Approach |
| :--- | :--- | :--- |
| *[Risk 1]* | *[Strategic impact]* | *[Mitigation strategy]* |
| *[Risk 2]* | *[Strategic impact]* | *[Mitigation strategy]* |

### 7.2 Strategic Opportunities
*[Instruction: Identify opportunities for enhanced strategic contribution beyond baseline objectives.]*

---

## 8. Strategic Communication Plan

### 8.1 Strategic Messaging
*[Instruction: Define key messages that communicate the project's strategic value to different audiences.]*

### 8.2 Strategic Reporting
*[Instruction: Outline how strategic progress and alignment will be communicated to leadership.]*

---

## 9. Strategic Review & Governance

### 9.1 Strategic Oversight
*[Instruction: Define the governance structure for ensuring continued strategic alignment throughout the project lifecycle.]*

### 9.2 Strategic Checkpoints
*[Instruction: Establish key checkpoints for reviewing and validating strategic alignment.]*

| Checkpoint | Timing | Review Focus | Decision Authority |
| :--- | :--- | :--- | :--- |
| *[Checkpoint 1]* | *[When]* | *[What to review]* | *[Who decides]* |
| *[Checkpoint 2]* | *[When]* | *[What to review]* | *[Who decides]* |

---

## 10. Conclusion & Strategic Commitment

*[Instruction: Conclude with a strong statement of strategic commitment and expected strategic value delivery. Reaffirm the project's importance to organizational success.]*

**Strategic Alignment Confirmation:** This project demonstrates clear alignment with organizational strategy and is positioned to deliver significant strategic value through ${this.context.projectName}.

---

**Document Approval:**
- **Strategic Sponsor:** *[Name and signature line]*
- **Project Sponsor:** *[Name and signature line]*
- **Portfolio Manager:** *[Name and signature line]*
- **Date:** *[Approval date]*
`;
  }
}