import type { ProjectContext } from '../../ai/types';

/**
 * @description A template for generating a Strategic Roadmap document.
 * It provides a structured format for outlining the high-level timeline,
 * milestones, and strategic phases of the project according to PMBOK standards.
 */
export class StrategicRoadmapTemplate {
  constructor(private context: ProjectContext) {}

  /**
   * Build the markdown content for Strategic Roadmap
   */
  generateContent(): string {
    const currentDate = new Date().toISOString();
    
    return `# Strategic Roadmap: ${this.context.projectName}

**Generated by:** ADPA (Automated Documentation Project Assistant)
**Category:** strategic-planning
**Generated:** ${currentDate}
**Version:** 1.0
**PMBOK Process Group:** Planning
**PMBOK Knowledge Area:** Project Schedule Management & Integration Management

---

## 1. Executive Summary

*[Instruction: Provide a high-level overview of the strategic roadmap, including the overall timeline, major phases, and key strategic milestones. This should give executives a clear understanding of the project's strategic journey.]*

---

## 2. Strategic Vision & Destination

### 2.1 Strategic Vision
*[Instruction: Articulate the strategic vision that this roadmap will achieve. Describe the desired future state and strategic outcomes.]*

### 2.2 Strategic Objectives
*[Instruction: List the key strategic objectives that the roadmap is designed to achieve.]*

1. **[Strategic Objective 1]:** *[Description and strategic importance]*
2. **[Strategic Objective 2]:** *[Description and strategic importance]*
3. **[Strategic Objective 3]:** *[Description and strategic importance]*

### 2.3 Success Criteria
*[Instruction: Define the criteria that will indicate successful completion of the strategic roadmap.]*

---

## 3. Roadmap Overview

### 3.1 Timeline Summary
*[Instruction: Provide a high-level timeline overview of the entire strategic roadmap.]*

| Phase | Duration | Start Date | End Date | Strategic Focus |
| :--- | :--- | :--- | :--- | :--- |
| **Phase 1: [Phase Name]** | *[Duration]* | *[Start date]* | *[End date]* | *[Strategic focus area]* |
| **Phase 2: [Phase Name]** | *[Duration]* | *[Start date]* | *[End date]* | *[Strategic focus area]* |
| **Phase 3: [Phase Name]** | *[Duration]* | *[Start date]* | *[End date]* | *[Strategic focus area]* |
| **Phase 4: [Phase Name]** | *[Duration]* | *[Start date]* | *[End date]* | *[Strategic focus area]* |

### 3.2 Strategic Phases
*[Instruction: Describe the strategic rationale for each phase and how they build upon each other.]*

---

## 4. Detailed Phase Planning

### 4.1 Phase 1: [Foundation/Discovery Phase Name]
*[Instruction: Provide detailed information about the first strategic phase.]*

#### Strategic Purpose
*[Instruction: Explain the strategic purpose and importance of this phase.]*

#### Key Objectives
- **[Objective 1]:** *[Description and deliverable]*
- **[Objective 2]:** *[Description and deliverable]*
- **[Objective 3]:** *[Description and deliverable]*

#### Major Deliverables
| Deliverable | Description | Strategic Value | Target Date |
| :--- | :--- | :--- | :--- |
| **[Deliverable 1]** | *[What it is]* | *[Strategic importance]* | *[Target date]* |
| **[Deliverable 2]** | *[What it is]* | *[Strategic importance]* | *[Target date]* |

#### Success Criteria
*[Instruction: Define specific success criteria for this phase.]*

#### Key Stakeholders
*[Instruction: Identify key stakeholders involved in this phase.]*

### 4.2 Phase 2: [Development/Implementation Phase Name]
*[Instruction: Provide detailed information about the second strategic phase.]*

#### Strategic Purpose
*[Instruction: Explain the strategic purpose and importance of this phase.]*

#### Key Objectives
- **[Objective 1]:** *[Description and deliverable]*
- **[Objective 2]:** *[Description and deliverable]*
- **[Objective 3]:** *[Description and deliverable]*

#### Major Deliverables
| Deliverable | Description | Strategic Value | Target Date |
| :--- | :--- | :--- | :--- |
| **[Deliverable 1]** | *[What it is]* | *[Strategic importance]* | *[Target date]* |
| **[Deliverable 2]** | *[What it is]* | *[Strategic importance]* | *[Target date]* |

#### Success Criteria
*[Instruction: Define specific success criteria for this phase.]*

#### Key Stakeholders
*[Instruction: Identify key stakeholders involved in this phase.]*

### 4.3 Phase 3: [Deployment/Launch Phase Name]
*[Instruction: Provide detailed information about the third strategic phase.]*

#### Strategic Purpose
*[Instruction: Explain the strategic purpose and importance of this phase.]*

#### Key Objectives
- **[Objective 1]:** *[Description and deliverable]*
- **[Objective 2]:** *[Description and deliverable]*
- **[Objective 3]:** *[Description and deliverable]*

#### Major Deliverables
| Deliverable | Description | Strategic Value | Target Date |
| :--- | :--- | :--- | :--- |
| **[Deliverable 1]** | *[What it is]* | *[Strategic importance]* | *[Target date]* |
| **[Deliverable 2]** | *[What it is]* | *[Strategic importance]* | *[Target date]* |

#### Success Criteria
*[Instruction: Define specific success criteria for this phase.]*

#### Key Stakeholders
*[Instruction: Identify key stakeholders involved in this phase.]*

### 4.4 Phase 4: [Optimization/Scaling Phase Name]
*[Instruction: Provide detailed information about the fourth strategic phase.]*

#### Strategic Purpose
*[Instruction: Explain the strategic purpose and importance of this phase.]*

#### Key Objectives
- **[Objective 1]:** *[Description and deliverable]*
- **[Objective 2]:** *[Description and deliverable]*
- **[Objective 3]:** *[Description and deliverable]*

#### Major Deliverables
| Deliverable | Description | Strategic Value | Target Date |
| :--- | :--- | :--- | :--- |
| **[Deliverable 1]** | *[What it is]* | *[Strategic importance]* | *[Target date]* |
| **[Deliverable 2]** | *[What it is]* | *[Strategic importance]* | *[Target date]* |

#### Success Criteria
*[Instruction: Define specific success criteria for this phase.]*

#### Key Stakeholders
*[Instruction: Identify key stakeholders involved in this phase.]*

---

## 5. Strategic Milestones

### 5.1 Major Strategic Milestones
*[Instruction: Define the major strategic milestones that mark significant progress toward strategic objectives.]*

| Milestone | Description | Strategic Significance | Target Date | Success Criteria |
| :--- | :--- | :--- | :--- | :--- |
| **[Milestone 1]** | *[What is achieved]* | *[Why strategically important]* | *[Target date]* | *[How success is measured]* |
| **[Milestone 2]** | *[What is achieved]* | *[Why strategically important]* | *[Target date]* | *[How success is measured]* |
| **[Milestone 3]** | *[What is achieved]* | *[Why strategically important]* | *[Target date]* | *[How success is measured]* |
| **[Milestone 4]** | *[What is achieved]* | *[Why strategically important]* | *[Target date]* | *[How success is measured]* |

### 5.2 Milestone Dependencies
*[Instruction: Identify critical dependencies between milestones and how they impact the strategic timeline.]*

---

## 6. Strategic Value Delivery Timeline

### 6.1 Value Realization Schedule
*[Instruction: Show when strategic value will be realized throughout the roadmap.]*

| Timeline | Value Category | Expected Value | Measurement Method |
| :--- | :--- | :--- | :--- |
| **Month 1-3** | *[Early value type]* | *[Expected early value]* | *[How measured]* |
| **Month 4-6** | *[Developing value type]* | *[Expected developing value]* | *[How measured]* |
| **Month 7-12** | *[Mature value type]* | *[Expected mature value]* | *[How measured]* |
| **Year 2+** | *[Sustained value type]* | *[Expected sustained value]* | *[How measured]* |

### 6.2 Quick Wins
*[Instruction: Identify early strategic wins that can be achieved quickly to build momentum.]*

1. **[Quick Win 1]:** *[Description, timeline, and strategic value]*
2. **[Quick Win 2]:** *[Description, timeline, and strategic value]*
3. **[Quick Win 3]:** *[Description, timeline, and strategic value]*

---

## 7. Resource & Investment Timeline

### 7.1 Resource Allocation by Phase
*[Instruction: Show how resources will be allocated across the strategic phases.]*

| Phase | Human Resources | Technology Investment | Budget Allocation | Strategic Rationale |
| :--- | :--- | :--- | :--- | :--- |
| **Phase 1** | *[Resource needs]* | *[Technology needs]* | *[Budget allocation]* | *[Why this investment]* |
| **Phase 2** | *[Resource needs]* | *[Technology needs]* | *[Budget allocation]* | *[Why this investment]* |
| **Phase 3** | *[Resource needs]* | *[Technology needs]* | *[Budget allocation]* | *[Why this investment]* |
| **Phase 4** | *[Resource needs]* | *[Technology needs]* | *[Budget allocation]* | *[Why this investment]* |

### 7.2 Investment Justification
*[Instruction: Justify the strategic investment pattern and timing.]*

---

## 8. Risk & Contingency Planning

### 8.1 Strategic Risks to Timeline
*[Instruction: Identify risks that could impact the strategic roadmap timeline.]*

| Risk | Impact on Roadmap | Probability | Mitigation Strategy | Contingency Plan |
| :--- | :--- | :--- | :--- | :--- |
| **[Risk 1]** | *[Timeline impact]* | *[High/Med/Low]* | *[Mitigation approach]* | *[Contingency approach]* |
| **[Risk 2]** | *[Timeline impact]* | *[High/Med/Low]* | *[Mitigation approach]* | *[Contingency approach]* |
| **[Risk 3]** | *[Timeline impact]* | *[High/Med/Low]* | *[Mitigation approach]* | *[Contingency approach]* |

### 8.2 Alternative Scenarios
*[Instruction: Describe alternative roadmap scenarios based on different risk outcomes.]*

---

## 9. Stakeholder Engagement Timeline

### 9.1 Stakeholder Involvement by Phase
*[Instruction: Map stakeholder engagement requirements across the strategic phases.]*

| Stakeholder Group | Phase 1 Role | Phase 2 Role | Phase 3 Role | Phase 4 Role |
| :--- | :--- | :--- | :--- | :--- |
| **[Stakeholder 1]** | *[Their role/involvement]* | *[Their role/involvement]* | *[Their role/involvement]* | *[Their role/involvement]* |
| **[Stakeholder 2]** | *[Their role/involvement]* | *[Their role/involvement]* | *[Their role/involvement]* | *[Their role/involvement]* |
| **[Stakeholder 3]** | *[Their role/involvement]* | *[Their role/involvement]* | *[Their role/involvement]* | *[Their role/involvement]* |

### 9.2 Communication Milestones
*[Instruction: Define key communication milestones throughout the roadmap.]*

---

## 10. Governance & Decision Points

### 10.1 Strategic Decision Points
*[Instruction: Identify key decision points that could affect the strategic direction or timeline.]*

| Decision Point | Timing | Decision Required | Decision Maker | Impact on Roadmap |
| :--- | :--- | :--- | :--- | :--- |
| **[Decision 1]** | *[When decision needed]* | *[What needs to be decided]* | *[Who decides]* | *[How it affects roadmap]* |
| **[Decision 2]** | *[When decision needed]* | *[What needs to be decided]* | *[Who decides]* | *[How it affects roadmap]* |

### 10.2 Governance Checkpoints
*[Instruction: Define regular governance checkpoints for reviewing roadmap progress.]*

---

## 11. Success Measurement & Monitoring

### 11.1 Progress Tracking Framework
*[Instruction: Define how progress against the strategic roadmap will be tracked and measured.]*

### 11.2 Course Correction Mechanisms
*[Instruction: Describe how the roadmap can be adjusted based on progress and changing conditions.]*

---

## 12. Future State Vision

### 12.1 End State Description
*[Instruction: Describe the desired end state that the roadmap will achieve.]*

### 12.2 Strategic Benefits Realized
*[Instruction: Summarize the strategic benefits that will be realized upon completion of the roadmap.]*

### 12.3 Next Phase Opportunities
*[Instruction: Identify potential next phase opportunities beyond this roadmap.]*

---

## 13. Implementation Readiness

### 13.1 Readiness Assessment
*[Instruction: Assess the organization's readiness to execute this strategic roadmap.]*

### 13.2 Success Factors
*[Instruction: Identify critical success factors for roadmap execution.]*

### 13.3 Implementation Recommendations
*[Instruction: Provide specific recommendations for successful roadmap implementation.]*

---

## 14. Conclusion & Next Steps

*[Instruction: Conclude with a summary of the strategic roadmap and immediate next steps for implementation.]*

**Strategic Commitment:** This roadmap provides a clear, strategic path for ${this.context.projectName} to achieve its strategic objectives and deliver maximum value to the organization.

**Immediate Next Steps:**
1. *[Next step 1]*
2. *[Next step 2]*
3. *[Next step 3]*

---

**Document Approval:**
- **Strategic Sponsor:** *[Name and signature line]*
- **Project Manager:** *[Name and signature line]*
- **Portfolio Manager:** *[Name and signature line]*
- **Date:** *[Approval date]*
`;
  }
}