import type { ProjectContext } from '../../ai/types';

/**
 * @description A template for generating a Strategic Success Metrics document.
 * It provides a structured format for defining high-level KPIs and success
 * measures that align with strategic objectives and PMBOK standards.
 */
export class StrategicSuccessMetricsTemplate {
  constructor(private context: ProjectContext) {}

  /**
   * Build the markdown content for Strategic Success Metrics
   */
  generateContent(): string {
    const currentDate = new Date().toISOString();
    
    return `# Strategic Success Metrics: ${this.context.projectName}

**Generated by:** ADPA (Automated Documentation Project Assistant)
**Category:** strategic-planning
**Generated:** ${currentDate}
**Version:** 1.0
**PMBOK Process Group:** Initiating & Monitoring/Controlling
**PMBOK Knowledge Area:** Project Performance Management

---

## 1. Executive Summary

*[Instruction: Provide a concise overview of the strategic success metrics framework for this project. Explain how these metrics align with organizational strategy and will be used to measure project success at the strategic level.]*

---

## 2. Strategic Success Framework

### 2.1 Success Definition
*[Instruction: Define what "success" means for this project from a strategic perspective. This should go beyond project delivery to include business outcomes and strategic impact.]*

### 2.2 Success Dimensions
*[Instruction: Identify the key dimensions of success for this project.]*

| Success Dimension | Description | Strategic Importance |
| :--- | :--- | :--- |
| **Financial Performance** | *[Financial outcomes and ROI]* | *[Why this matters strategically]* |
| **Operational Excellence** | *[Operational improvements and efficiency]* | *[Strategic operational impact]* |
| **Strategic Positioning** | *[Market position and competitive advantage]* | *[Strategic positioning value]* |
| **Stakeholder Satisfaction** | *[Stakeholder value and satisfaction]* | *[Strategic stakeholder importance]* |
| **Innovation & Growth** | *[Innovation capabilities and growth potential]* | *[Strategic innovation value]* |

### 2.3 Success Hierarchy
*[Instruction: Show the relationship between project outputs, outcomes, and strategic benefits.]*

```
Strategic Benefits (Why)
    ↑
Business Outcomes (What)
    ↑
Project Outputs (How)
```

---

## 3. Strategic Key Performance Indicators (KPIs)

### 3.1 Primary Strategic KPIs
*[Instruction: Define the most important KPIs that measure strategic success.]*

#### KPI 1: [Primary Strategic KPI Name]
- **Definition:** *[Clear definition of what this KPI measures]*
- **Strategic Alignment:** *[How this KPI aligns with organizational strategy]*
- **Measurement Method:** *[How the KPI will be calculated and measured]*
- **Data Source:** *[Where the data comes from]*
- **Baseline Value:** *[Current state measurement]*
- **Target Value:** *[Expected target after project completion]*
- **Stretch Goal:** *[Aspirational target if everything goes exceptionally well]*
- **Measurement Frequency:** *[How often this will be measured]*
- **Responsible Party:** *[Who is accountable for this KPI]*

#### KPI 2: [Secondary Strategic KPI Name]
- **Definition:** *[Clear definition of what this KPI measures]*
- **Strategic Alignment:** *[How this KPI aligns with organizational strategy]*
- **Measurement Method:** *[How the KPI will be calculated and measured]*
- **Data Source:** *[Where the data comes from]*
- **Baseline Value:** *[Current state measurement]*
- **Target Value:** *[Expected target after project completion]*
- **Stretch Goal:** *[Aspirational target if everything goes exceptionally well]*
- **Measurement Frequency:** *[How often this will be measured]*
- **Responsible Party:** *[Who is accountable for this KPI]*

#### KPI 3: [Additional Strategic KPI Name]
- **Definition:** *[Clear definition of what this KPI measures]*
- **Strategic Alignment:** *[How this KPI aligns with organizational strategy]*
- **Measurement Method:** *[How the KPI will be calculated and measured]*
- **Data Source:** *[Where the data comes from]*
- **Baseline Value:** *[Current state measurement]*
- **Target Value:** *[Expected target after project completion]*
- **Stretch Goal:** *[Aspirational target if everything goes exceptionally well]*
- **Measurement Frequency:** *[How often this will be measured]*
- **Responsible Party:** *[Who is accountable for this KPI]*

### 3.2 Supporting KPIs
*[Instruction: Define additional KPIs that support the primary strategic KPIs.]*

| KPI Name | Measurement | Target | Frequency | Owner |
| :--- | :--- | :--- | :--- | :--- |
| *[Supporting KPI 1]* | *[How measured]* | *[Target value]* | *[Frequency]* | *[Responsible party]* |
| *[Supporting KPI 2]* | *[How measured]* | *[Target value]* | *[Frequency]* | *[Responsible party]* |
| *[Supporting KPI 3]* | *[How measured]* | *[Target value]* | *[Frequency]* | *[Responsible party]* |

---

## 4. Success Metrics by Category

### 4.1 Financial Success Metrics
*[Instruction: Define financial metrics that demonstrate strategic financial success.]*

| Metric | Definition | Target | Measurement Method |
| :--- | :--- | :--- | :--- |
| **Return on Investment (ROI)** | *[ROI calculation method]* | *[Target ROI %]* | *[How calculated]* |
| **Net Present Value (NPV)** | *[NPV calculation method]* | *[Target NPV]* | *[How calculated]* |
| **Cost Savings** | *[Cost reduction measurement]* | *[Target savings]* | *[How measured]* |
| **Revenue Impact** | *[Revenue increase measurement]* | *[Target revenue]* | *[How measured]* |

### 4.2 Operational Success Metrics
*[Instruction: Define operational metrics that demonstrate strategic operational success.]*

| Metric | Definition | Target | Measurement Method |
| :--- | :--- | :--- | :--- |
| **Process Efficiency** | *[Efficiency measurement]* | *[Target improvement]* | *[How measured]* |
| **Quality Improvement** | *[Quality measurement]* | *[Target quality level]* | *[How measured]* |
| **Time Reduction** | *[Time savings measurement]* | *[Target time savings]* | *[How measured]* |
| **Resource Utilization** | *[Resource efficiency measurement]* | *[Target utilization]* | *[How measured]* |

### 4.3 Strategic Positioning Metrics
*[Instruction: Define metrics that demonstrate improved strategic positioning.]*

| Metric | Definition | Target | Measurement Method |
| :--- | :--- | :--- | :--- |
| **Market Share** | *[Market position measurement]* | *[Target market share]* | *[How measured]* |
| **Competitive Advantage** | *[Competitive position measurement]* | *[Target advantage]* | *[How measured]* |
| **Innovation Index** | *[Innovation capability measurement]* | *[Target innovation level]* | *[How measured]* |
| **Strategic Readiness** | *[Future readiness measurement]* | *[Target readiness level]* | *[How measured]* |

### 4.4 Stakeholder Success Metrics
*[Instruction: Define metrics that demonstrate stakeholder value and satisfaction.]*

| Metric | Definition | Target | Measurement Method |
| :--- | :--- | :--- | :--- |
| **Customer Satisfaction** | *[Customer satisfaction measurement]* | *[Target satisfaction score]* | *[How measured]* |
| **Employee Engagement** | *[Employee engagement measurement]* | *[Target engagement level]* | *[How measured]* |
| **Stakeholder Value** | *[Stakeholder value measurement]* | *[Target value delivery]* | *[How measured]* |
| **User Adoption** | *[Adoption rate measurement]* | *[Target adoption rate]* | *[How measured]* |

---

## 5. Success Measurement Timeline

### 5.1 Measurement Roadmap
*[Instruction: Create a timeline showing when different success metrics will be measured and evaluated.]*

| Timeline | Measurement Focus | Key Metrics | Success Criteria |
| :--- | :--- | :--- | :--- |
| **Month 1-3** | *[Early indicators]* | *[Early metrics]* | *[Early success criteria]* |
| **Month 4-6** | *[Progress indicators]* | *[Progress metrics]* | *[Progress success criteria]* |
| **Month 7-12** | *[Outcome indicators]* | *[Outcome metrics]* | *[Outcome success criteria]* |
| **Year 2+** | *[Strategic impact indicators]* | *[Strategic metrics]* | *[Strategic success criteria]* |

### 5.2 Milestone Success Criteria
*[Instruction: Define specific success criteria for key project milestones.]*

| Milestone | Success Criteria | Measurement Method | Target Date |
| :--- | :--- | :--- | :--- |
| **[Milestone 1]** | *[What success looks like]* | *[How measured]* | *[Target date]* |
| **[Milestone 2]** | *[What success looks like]* | *[How measured]* | *[Target date]* |
| **[Milestone 3]** | *[What success looks like]* | *[How measured]* | *[Target date]* |

---

## 6. Success Measurement Framework

### 6.1 Data Collection Plan
*[Instruction: Define how success data will be collected, stored, and analyzed.]*

| Data Element | Collection Method | Frequency | Responsible Party | Storage Location |
| :--- | :--- | :--- | :--- | :--- |
| *[Data 1]* | *[Collection method]* | *[How often]* | *[Who collects]* | *[Where stored]* |
| *[Data 2]* | *[Collection method]* | *[How often]* | *[Who collects]* | *[Where stored]* |
| *[Data 3]* | *[Collection method]* | *[How often]* | *[Who collects]* | *[Where stored]* |

### 6.2 Analysis & Reporting Framework
*[Instruction: Define how success data will be analyzed and reported.]*

### 6.3 Success Dashboard Design
*[Instruction: Describe the design and content of the strategic success dashboard.]*

---

## 7. Success Governance

### 7.1 Success Oversight Structure
*[Instruction: Define the governance structure for monitoring and ensuring strategic success.]*

| Role | Responsibilities | Success Accountabilities |
| :--- | :--- | :--- |
| **Success Owner** | *[Primary responsibilities]* | *[What they're accountable for]* |
| **Strategic Sponsor** | *[Sponsor responsibilities]* | *[Sponsor accountabilities]* |
| **Project Manager** | *[PM responsibilities]* | *[PM accountabilities]* |
| **Success Analyst** | *[Analyst responsibilities]* | *[Analyst accountabilities]* |

### 7.2 Success Review Process
*[Instruction: Define the process for regularly reviewing strategic success metrics.]*

### 7.3 Success Reporting
*[Instruction: Outline how success progress will be reported and to whom.]*

| Report Type | Audience | Frequency | Content Focus |
| :--- | :--- | :--- | :--- |
| **Strategic Success Dashboard** | *[Executive leadership]* | *[Real-time/Weekly]* | *[High-level strategic metrics]* |
| **Success Analysis Report** | *[Project stakeholders]* | *[Monthly]* | *[Detailed success analysis]* |
| **Strategic Success Review** | *[Steering committee]* | *[Quarterly]* | *[Comprehensive success evaluation]* |

---

## 8. Success Risk Management

### 8.1 Success Risks
*[Instruction: Identify risks that could prevent achieving strategic success.]*

| Risk | Impact on Success | Probability | Mitigation Strategy |
| :--- | :--- | :--- | :--- |
| *[Risk 1]* | *[How it affects success]* | *[High/Med/Low]* | *[Mitigation approach]* |
| *[Risk 2]* | *[How it affects success]* | *[High/Med/Low]* | *[Mitigation approach]* |
| *[Risk 3]* | *[How it affects success]* | *[High/Med/Low]* | *[Mitigation approach]* |

### 8.2 Success Contingency Planning
*[Instruction: Describe contingency plans if success metrics are not being achieved.]*

---

## 9. Success Optimization

### 9.1 Success Enhancement Opportunities
*[Instruction: Identify opportunities to enhance or accelerate success achievement.]*

### 9.2 Continuous Improvement
*[Instruction: Describe how the success measurement framework will be continuously improved.]*

---

## 10. Success Communication Strategy

### 10.1 Success Messaging
*[Instruction: Define key messages for communicating success to different audiences.]*

### 10.2 Success Celebration Plan
*[Instruction: Describe how success achievements will be recognized and celebrated.]*

---

## 11. Long-term Success Sustainability

### 11.1 Sustained Success Plan
*[Instruction: Describe how strategic success will be sustained after project completion.]*

### 11.2 Success Evolution
*[Instruction: Outline how success metrics may evolve over time as the organization grows and changes.]*

---

## 12. Conclusion & Success Commitment

*[Instruction: Conclude with a strong commitment to achieving strategic success and the value of the measurement framework.]*

**Success Commitment:** This Strategic Success Metrics framework establishes a comprehensive approach to measuring and ensuring the strategic success of ${this.context.projectName}, providing clear accountability and visibility into value delivery.

---

**Document Approval:**
- **Success Owner:** *[Name and signature line]*
- **Strategic Sponsor:** *[Name and signature line]*
- **Project Manager:** *[Name and signature line]*
- **Date:** *[Approval date]*
`;
  }
}