import type { ProjectContext } from '../../ai/types';

/**
 * @description A template for generating a Value Proposition document.
 * It provides a structured format for articulating the unique value
 * and competitive advantage that the project will deliver.
 */
export class ValuePropositionTemplate {
  constructor(private context: ProjectContext) {}

  /**
   * Build the markdown content for Value Proposition
   */
  generateContent(): string {
    const currentDate = new Date().toISOString();
    
    return `# Value Proposition: ${this.context.projectName}

**Generated by:** ADPA (Automated Documentation Project Assistant)
**Category:** strategic-planning
**Generated:** ${currentDate}
**Version:** 1.0
**PMBOK Process Group:** Initiating
**PMBOK Knowledge Area:** Project Integration Management

---

## 1. Executive Summary

*[Instruction: Provide a compelling, concise statement of the unique value this project will deliver. This should be a clear, memorable value proposition that can be communicated to any stakeholder in 30 seconds or less.]*

**Value Proposition Statement:** *[One-sentence summary of the unique value delivered by this project]*

---

## 2. Problem Statement & Market Need

### 2.1 Current State Analysis
*[Instruction: Describe the current situation, pain points, and challenges that create the need for this project. Quantify the problem where possible.]*

### 2.2 Market Opportunity
*[Instruction: Describe the market opportunity or business need that this project addresses. Include market size, trends, or competitive factors where relevant.]*

### 2.3 Cost of Inaction
*[Instruction: Articulate what happens if this project is not undertaken. Quantify the cost of maintaining the status quo.]*

| Impact Area | Cost of Inaction | Quantified Impact |
| :--- | :--- | :--- |
| **Financial** | *[Revenue loss, increased costs]* | *[Dollar amount or percentage]* |
| **Operational** | *[Inefficiencies, manual processes]* | *[Time, resources, quality impact]* |
| **Strategic** | *[Competitive disadvantage, missed opportunities]* | *[Market share, positioning impact]* |
| **Risk** | *[Compliance, security, operational risks]* | *[Risk exposure quantification]* |

---

## 3. Solution Overview

### 3.1 Proposed Solution
*[Instruction: Describe the proposed solution in business terms, focusing on what it does and how it addresses the identified problems.]*

### 3.2 Unique Differentiators
*[Instruction: Identify what makes this solution unique or superior to alternatives.]*

1. **[Differentiator 1]:** *[Description and competitive advantage]*
2. **[Differentiator 2]:** *[Description and competitive advantage]*
3. **[Differentiator 3]:** *[Description and competitive advantage]*

### 3.3 Solution Capabilities
*[Instruction: List the key capabilities that the solution will provide.]*

| Capability | Description | Business Value |
| :--- | :--- | :--- |
| **[Capability 1]** | *[What it does]* | *[Value it provides]* |
| **[Capability 2]** | *[What it does]* | *[Value it provides]* |
| **[Capability 3]** | *[What it does]* | *[Value it provides]* |

---

## 4. Value Delivery Framework

### 4.1 Value Categories
*[Instruction: Categorize the different types of value this project will deliver.]*

#### Financial Value
- **Revenue Impact:** *[How the project will increase revenue]*
- **Cost Reduction:** *[How the project will reduce costs]*
- **Efficiency Gains:** *[How the project will improve efficiency]*
- **ROI Projection:** *[Expected return on investment]*

#### Operational Value
- **Process Improvements:** *[How processes will be enhanced]*
- **Quality Enhancements:** *[How quality will be improved]*
- **Speed/Time Savings:** *[How time will be saved]*
- **Resource Optimization:** *[How resources will be better utilized]*

#### Strategic Value
- **Competitive Advantage:** *[How this creates competitive advantage]*
- **Market Position:** *[How this improves market position]*
- **Innovation Capability:** *[How this enhances innovation]*
- **Future Readiness:** *[How this prepares for the future]*

#### Risk Value
- **Risk Mitigation:** *[What risks are reduced or eliminated]*
- **Compliance Benefits:** *[How compliance is improved]*
- **Security Enhancements:** *[How security is strengthened]*
- **Business Continuity:** *[How business continuity is enhanced]*

### 4.2 Value Quantification
*[Instruction: Provide specific, quantified value estimates where possible.]*

| Value Type | Quantified Benefit | Measurement Method | Confidence Level |
| :--- | :--- | :--- | :--- |
| **[Value 1]** | *[Specific amount/percentage]* | *[How measured]* | *[High/Medium/Low]* |
| **[Value 2]** | *[Specific amount/percentage]* | *[How measured]* | *[High/Medium/Low]* |
| **[Value 3]** | *[Specific amount/percentage]* | *[How measured]* | *[High/Medium/Low]* |

---

## 5. Stakeholder Value Analysis

### 5.1 Stakeholder Value Mapping
*[Instruction: Map specific value propositions to different stakeholder groups.]*

| Stakeholder Group | Primary Value Received | Secondary Benefits | Value Realization Timeline |
| :--- | :--- | :--- | :--- |
| **[Stakeholder 1]** | *[Main value for them]* | *[Additional benefits]* | *[When they see value]* |
| **[Stakeholder 2]** | *[Main value for them]* | *[Additional benefits]* | *[When they see value]* |
| **[Stakeholder 3]** | *[Main value for them]* | *[Additional benefits]* | *[When they see value]* |

### 5.2 Customer/End-User Value
*[Instruction: Specifically describe the value delivered to customers or end-users.]*

### 5.3 Internal Stakeholder Value
*[Instruction: Describe the value delivered to internal stakeholders and teams.]*

---

## 6. Competitive Analysis

### 6.1 Alternative Solutions
*[Instruction: Identify alternative approaches or solutions and compare their value propositions.]*

| Alternative | Pros | Cons | Value Comparison |
| :--- | :--- | :--- | :--- |
| **[Alternative 1]** | *[Advantages]* | *[Disadvantages]* | *[How our solution is better]* |
| **[Alternative 2]** | *[Advantages]* | *[Disadvantages]* | *[How our solution is better]* |
| **Status Quo** | *[Advantages of doing nothing]* | *[Disadvantages of doing nothing]* | *[Why change is necessary]* |

### 6.2 Competitive Advantages
*[Instruction: Clearly articulate why this solution is superior to alternatives.]*

---

## 7. Value Realization Timeline

### 7.1 Value Delivery Roadmap
*[Instruction: Show when different value components will be realized throughout the project lifecycle.]*

| Phase | Timeline | Value Delivered | Cumulative Value |
| :--- | :--- | :--- | :--- |
| **Phase 1** | *[Timeframe]* | *[Early value delivered]* | *[Total value to date]* |
| **Phase 2** | *[Timeframe]* | *[Additional value delivered]* | *[Total value to date]* |
| **Phase 3** | *[Timeframe]* | *[Final value delivered]* | *[Total project value]* |
| **Post-Project** | *[Ongoing]* | *[Sustained/growing value]* | *[Long-term value]* |

### 7.2 Quick Wins
*[Instruction: Identify early, visible wins that demonstrate value quickly.]*

1. **[Quick Win 1]:** *[Description and timeline]*
2. **[Quick Win 2]:** *[Description and timeline]*
3. **[Quick Win 3]:** *[Description and timeline]*

---

## 8. Investment & Value Equation

### 8.1 Investment Requirements
*[Instruction: Summarize the total investment required for the project.]*

| Investment Category | Amount | Justification |
| :--- | :--- | :--- |
| **Initial Investment** | *[Amount]* | *[What this covers]* |
| **Ongoing Costs** | *[Amount/period]* | *[What this covers]* |
| **Total 3-Year Investment** | *[Amount]* | *[Total cost of ownership]* |

### 8.2 Value-to-Investment Ratio
*[Instruction: Calculate and present the value-to-investment ratio.]*

- **Total Investment:** *[Amount]*
- **Total Value (3 years):** *[Amount]*
- **Value-to-Investment Ratio:** *[Ratio]*
- **Net Value:** *[Total value minus total investment]*

---

## 9. Risk & Value Protection

### 9.1 Value Risks
*[Instruction: Identify risks that could impact value delivery.]*

| Risk | Impact on Value | Mitigation Strategy |
| :--- | :--- | :--- |
| **[Risk 1]** | *[How it affects value]* | *[How to mitigate]* |
| **[Risk 2]** | *[How it affects value]* | *[How to mitigate]* |
| **[Risk 3]** | *[How it affects value]* | *[How to mitigate]* |

### 9.2 Value Assurance
*[Instruction: Describe measures to ensure value is delivered as promised.]*

---

## 10. Success Metrics & Value Validation

### 10.1 Value Metrics
*[Instruction: Define specific metrics that will validate value delivery.]*

| Metric | Target | Measurement Method | Review Frequency |
| :--- | :--- | :--- | :--- |
| **[Metric 1]** | *[Target value]* | *[How measured]* | *[How often]* |
| **[Metric 2]** | *[Target value]* | *[How measured]* | *[How often]* |
| **[Metric 3]** | *[Target value]* | *[How measured]* | *[How often]* |

### 10.2 Value Validation Process
*[Instruction: Describe how value delivery will be validated and confirmed.]*

---

## 11. Communication Strategy

### 11.1 Value Messaging
*[Instruction: Define key messages for communicating the value proposition to different audiences.]*

### 11.2 Value Demonstration
*[Instruction: Describe how value will be demonstrated and communicated throughout the project.]*

---

## 12. Conclusion & Call to Action

*[Instruction: Conclude with a compelling summary of the value proposition and a clear call to action for stakeholders.]*

**Value Commitment:** ${this.context.projectName} represents a compelling value proposition that will deliver significant, measurable benefits to the organization while positioning us for future success.

**Recommended Action:** *[Clear recommendation for next steps]*

---

**Document Approval:**
- **Value Owner:** *[Name and signature line]*
- **Project Sponsor:** *[Name and signature line]*
- **Business Stakeholder:** *[Name and signature line]*
- **Date:** *[Approval date]*
`;
  }
}