import type { ProjectContext } from '../../ai/types';

/**
 * Stakeholderengagementplan Template generates the content for the Stakeholderengagementplan document.
 */
export class StakeholderengagementplanTemplate {
  constructor(private context: ProjectContext) {}

  /**
   * Build the markdown content for Stakeholder Engagement Plan
   */
  generateContent(): string {
    const projectName = this.context.projectName || 'Project';
    const projectType = this.context.projectType || 'Strategic Initiative';
    
    return `# Stakeholder Engagement Plan

**Generated by Requirements Gathering Agent v2.1.3**  
**Category:** stakeholder-management  
**Generated:** ${new Date().toISOString()}  
**Description:** Comprehensive stakeholder engagement plan for clear project charters and effective stakeholder participation

---

## 🎯 **ENGAGEMENT OBJECTIVES**

**MISSION**: Create a comprehensive stakeholder engagement strategy that ensures clear project charter understanding, confident sponsor authorization, and effective stakeholder participation throughout the project lifecycle.

**KEY FOCUS AREAS**:
1. **Sponsor Authorization Support** → Strategies to help sponsors understand and authorize projects confidently
2. **Stakeholder Participation Excellence** → Tailored approaches that drive meaningful stakeholder engagement
3. **Communication Effectiveness** → Clear, targeted communication strategies for diverse stakeholder needs
4. **Change Management Success** → Proactive engagement that builds support and manages resistance

---

# Stakeholder Engagement Plan - ${projectName}

**Project Title:** ${projectName}  
**Project Type:** ${projectType}  
**Plan Date:** ${new Date().toISOString().split('T')[0]}  
**Stakeholder Manager:** [STAKEHOLDER MANAGER NAME]  
**Project Manager:** [PROJECT MANAGER NAME]

---

## Executive Summary

**Plan Purpose:**  
[AI_SYNTHESIS: Define the purpose of this engagement plan and how it supports project charter clarity and stakeholder participation]

**Key Engagement Objectives:**  
[AI_SYNTHESIS: Identify the primary engagement objectives aligned with project success and stakeholder needs]

**Critical Success Factors:**  
[AI_SYNTHESIS: Define the most important factors for successful stakeholder engagement throughout the project]

---

## 1. Stakeholder Engagement Strategy Overview

### Engagement Philosophy
**Overall Approach:**  
[AI_SYNTHESIS: Define the comprehensive approach to stakeholder engagement for this specific project]

**Guiding Principles:**
- **Transparency:** [AI_SYNTHESIS: How transparency will be maintained with all stakeholders]
- **Inclusivity:** [AI_SYNTHESIS: How diverse stakeholder perspectives will be included and valued]
- **Responsiveness:** [AI_SYNTHESIS: How stakeholder feedback will be addressed promptly and effectively]
- **Value Creation:** [AI_SYNTHESIS: How engagement will create tangible value for stakeholders]

### Engagement Objectives by Stakeholder Category
**Executive Sponsors:**
- **Charter Authorization:** [AI_SYNTHESIS: Specific objectives for sponsor charter understanding and confident authorization]
- **Strategic Alignment:** [AI_SYNTHESIS: Objectives for maintaining strategic alignment and ongoing support]
- **Resource Commitment:** [AI_SYNTHESIS: Objectives for securing and maintaining necessary resource commitments]

**Project Stakeholders:**
- **Active Participation:** [AI_SYNTHESIS: Objectives for meaningful stakeholder participation in project activities]
- **Requirements Validation:** [AI_SYNTHESIS: Objectives for stakeholder input on requirements and solution validation]
- **Change Adoption:** [AI_SYNTHESIS: Objectives for successful stakeholder adoption and change management]

**End Users:**
- **User Adoption:** [AI_SYNTHESIS: Objectives for end user engagement and successful system/process adoption]
- **Feedback Integration:** [AI_SYNTHESIS: Objectives for incorporating user feedback into project deliverables]
- **Training and Support:** [AI_SYNTHESIS: Objectives for comprehensive user training and ongoing support]

---

## 2. Sponsor Engagement Strategy

### Executive Sponsor Engagement Framework
**Charter Authorization Support:**
- **Information Provision:** [AI_SYNTHESIS: Define comprehensive information sponsors need for confident project authorization]
- **Risk Communication:** [AI_SYNTHESIS: Specify how risks will be communicated to build sponsor confidence and trust]
- **Success Criteria Alignment:** [AI_SYNTHESIS: Describe how success criteria will be aligned with sponsor expectations and organizational goals]

**Ongoing Sponsor Engagement:**
- **Progress Reporting:** [AI_SYNTHESIS: Define sponsor progress reporting approach, frequency, and content requirements]
- **Strategic Alignment Reviews:** [AI_SYNTHESIS: Specify strategic alignment review processes and decision points]
- **Escalation Management:** [AI_SYNTHESIS: Describe clear escalation procedures for sponsor involvement and decision-making]

### Sponsor Communication Plan
| Communication Type | Frequency | Format | Content Focus | Success Criteria |
|-------------------|-----------|---------|---------------|------------------|
| Charter Review | [AI_SYNTHESIS: Frequency] | [AI_SYNTHESIS: Format] | [AI_SYNTHESIS: Content] | [AI_SYNTHESIS: Success Criteria] |
| Progress Updates | [AI_SYNTHESIS: Frequency] | [AI_SYNTHESIS: Format] | [AI_SYNTHESIS: Content] | [AI_SYNTHESIS: Success Criteria] |
| Strategic Reviews | [AI_SYNTHESIS: Frequency] | [AI_SYNTHESIS: Format] | [AI_SYNTHESIS: Content] | [AI_SYNTHESIS: Success Criteria] |
| Issue Escalations | As Needed | [AI_SYNTHESIS: Format] | [AI_SYNTHESIS: Content] | [AI_SYNTHESIS: Success Criteria] |

---

## 3. Stakeholder-Specific Engagement Strategies

### High-Power, High-Interest Stakeholders (Manage Closely)
**Engagement Approach:**
- **Involvement Level:** [AI_SYNTHESIS: Define appropriate level of involvement and decision-making participation]
- **Communication Frequency:** [AI_SYNTHESIS: Specify optimal communication frequency and preferred methods]
- **Feedback Integration:** [AI_SYNTHESIS: Describe comprehensive feedback collection and integration processes]

**Specific Strategies by Stakeholder Type:**
- **[Stakeholder Type 1]:** [AI_SYNTHESIS: Tailored engagement strategy and specific tactics]
- **[Stakeholder Type 2]:** [AI_SYNTHESIS: Tailored engagement strategy and specific tactics]
- **[Stakeholder Type 3]:** [AI_SYNTHESIS: Tailored engagement strategy and specific tactics]

### High-Power, Low-Interest Stakeholders (Keep Satisfied)
**Engagement Approach:**
- **Information Provision:** [AI_SYNTHESIS: Define strategic information sharing approach to maintain satisfaction]
- **Consultation Timing:** [AI_SYNTHESIS: Specify optimal timing and methods for stakeholder consultation]
- **Influence Management:** [AI_SYNTHESIS: Describe strategies to maintain positive influence and support]

**Specific Strategies by Stakeholder Type:**
- **[Stakeholder Type 1]:** [AI_SYNTHESIS: Tailored engagement strategy and specific tactics]
- **[Stakeholder Type 2]:** [AI_SYNTHESIS: Tailored engagement strategy and specific tactics]

### Low-Power, High-Interest Stakeholders (Keep Informed)
**Engagement Approach:**
- **Information Sharing:** [AI_SYNTHESIS: Define comprehensive information sharing approach and content]
- **Participation Opportunities:** [AI_SYNTHESIS: Specify meaningful participation opportunities and involvement methods]
- **Feedback Mechanisms:** [AI_SYNTHESIS: Describe effective feedback collection and response processes]

**Specific Strategies by Stakeholder Type:**
- **[Stakeholder Type 1]:** [AI_SYNTHESIS: Tailored engagement strategy and specific tactics]
- **[Stakeholder Type 2]:** [AI_SYNTHESIS: Tailored engagement strategy and specific tactics]

### Low-Power, Low-Interest Stakeholders (Monitor)
**Engagement Approach:**
- **Monitoring Strategy:** [AI_SYNTHESIS: Define appropriate monitoring strategy and frequency]
- **Communication Method:** [AI_SYNTHESIS: Specify minimal but effective communication approach]
- **Escalation Triggers:** [AI_SYNTHESIS: Identify clear triggers for when increased engagement is needed]

---

## 4. Communication Strategy and Protocols

### Communication Framework
**Communication Principles:**
- **Clarity:** [AI_SYNTHESIS: How messages will be clear, understandable, and actionable]
- **Relevance:** [AI_SYNTHESIS: How communication will be relevant and valuable to each stakeholder]
- **Timeliness:** [AI_SYNTHESIS: How timely and appropriate communication timing will be ensured]
- **Two-Way Communication:** [AI_SYNTHESIS: How effective two-way communication will be facilitated]

### Comprehensive Communication Matrix
| Stakeholder Group | Primary Channel | Secondary Channel | Frequency | Content Type | Responsible Party |
|-------------------|----------------|-------------------|-----------|--------------|-------------------|
| Executive Sponsors | [AI_SYNTHESIS: Channel] | [AI_SYNTHESIS: Channel] | [AI_SYNTHESIS: Frequency] | [AI_SYNTHESIS: Content] | [AI_SYNTHESIS: Person] |
| Project Team | [AI_SYNTHESIS: Channel] | [AI_SYNTHESIS: Channel] | [AI_SYNTHESIS: Frequency] | [AI_SYNTHESIS: Content] | [AI_SYNTHESIS: Person] |
| End Users | [AI_SYNTHESIS: Channel] | [AI_SYNTHESIS: Channel] | [AI_SYNTHESIS: Frequency] | [AI_SYNTHESIS: Content] | [AI_SYNTHESIS: Person] |
| SMEs | [AI_SYNTHESIS: Channel] | [AI_SYNTHESIS: Channel] | [AI_SYNTHESIS: Frequency] | [AI_SYNTHESIS: Content] | [AI_SYNTHESIS: Person] |

### Message Customization by Stakeholder Type
**Executive Level Messages:**
- **Focus:** [AI_SYNTHESIS: Strategic impact, ROI, risk management, and organizational value]
- **Format:** [AI_SYNTHESIS: Executive summaries, dashboards, briefings, and strategic reports]
- **Language:** [AI_SYNTHESIS: Business-focused, outcome-oriented, and decision-supporting]

**Operational Level Messages:**
- **Focus:** [AI_SYNTHESIS: Implementation details, process changes, training, and operational impact]
- **Format:** [AI_SYNTHESIS: Detailed documentation, workshops, training materials, and process guides]
- **Language:** [AI_SYNTHESIS: Technical, process-oriented, practical, and implementation-focused]

**End User Messages:**
- **Focus:** [AI_SYNTHESIS: Benefits, changes, support available, and user impact]
- **Format:** [AI_SYNTHESIS: User guides, FAQs, help documentation, and training materials]
- **Language:** [AI_SYNTHESIS: User-friendly, benefit-focused, supportive, and encouraging]

---

## 5. Engagement Activities and Timeline

### Project Phase-Based Engagement

#### Initiation Phase
**Sponsor Engagement Activities:**
- **Charter Review Sessions:** [AI_SYNTHESIS: Detailed schedule and approach for charter review with sponsors]
- **Authorization Meetings:** [AI_SYNTHESIS: Comprehensive process for securing formal project authorization]
- **Stakeholder Identification:** [AI_SYNTHESIS: Systematic process for identifying and confirming all project stakeholders]

**Stakeholder Engagement Activities:**
- **Stakeholder Kickoff:** [AI_SYNTHESIS: Initial stakeholder engagement and comprehensive orientation activities]
- **Expectation Setting:** [AI_SYNTHESIS: Structured process for setting and aligning stakeholder expectations]
- **Communication Setup:** [AI_SYNTHESIS: Establishment of communication channels, protocols, and feedback mechanisms]

#### Planning Phase
**Sponsor Engagement Activities:**
- **Planning Reviews:** [AI_SYNTHESIS: Sponsor involvement in planning validation, approval, and strategic alignment]
- **Resource Confirmation:** [AI_SYNTHESIS: Comprehensive process for confirming and securing resource commitments]
- **Risk Review:** [AI_SYNTHESIS: Sponsor review and approval of risk management approaches and mitigation strategies]

**Stakeholder Engagement Activities:**
- **Requirements Gathering:** [AI_SYNTHESIS: Stakeholder involvement in requirements definition, validation, and approval]
- **Solution Design Input:** [AI_SYNTHESIS: Stakeholder participation in solution design, review, and feedback]
- **Change Impact Assessment:** [AI_SYNTHESIS: Stakeholder assessment of change impacts and mitigation planning]

#### Execution Phase
**Sponsor Engagement Activities:**
- **Progress Reviews:** [AI_SYNTHESIS: Regular sponsor progress reviews, decision points, and strategic guidance]
- **Issue Escalation:** [AI_SYNTHESIS: Clear process for escalating issues requiring sponsor attention and decision-making]
- **Milestone Approvals:** [AI_SYNTHESIS: Sponsor approval processes for major milestones and deliverable acceptance]

**Stakeholder Engagement Activities:**
- **Regular Updates:** [AI_SYNTHESIS: Ongoing stakeholder communication, updates, and progress sharing]
- **Feedback Collection:** [AI_SYNTHESIS: Systematic feedback collection, analysis, and integration processes]
- **Change Management:** [AI_SYNTHESIS: Ongoing change management, adoption support, and resistance management]

#### Closing Phase
**Sponsor Engagement Activities:**
- **Success Validation:** [AI_SYNTHESIS: Sponsor validation of project success, outcomes, and value delivery]
- **Lessons Learned:** [AI_SYNTHESIS: Sponsor participation in lessons learned capture and improvement identification]
- **Transition Planning:** [AI_SYNTHESIS: Sponsor approval of transition plans and ongoing support arrangements]

**Stakeholder Engagement Activities:**
- **Outcome Communication:** [AI_SYNTHESIS: Communication of project outcomes, benefits realized, and success stories]
- **Transition Support:** [AI_SYNTHESIS: Support for stakeholders in transitioning to new processes, systems, or ways of working]
- **Ongoing Relationship:** [AI_SYNTHESIS: Establishment of ongoing stakeholder relationship management and support]

---

## 6. Success Metrics and Monitoring

### Engagement Success Metrics
**Quantitative Metrics:**
- **Participation Rates:** [AI_SYNTHESIS: Target participation rates by stakeholder group and activity type]
- **Communication Effectiveness:** [AI_SYNTHESIS: Response rates, feedback quality, satisfaction scores, and engagement levels]
- **Milestone Achievement:** [AI_SYNTHESIS: On-time achievement of engagement milestones and deliverable acceptance]

**Qualitative Metrics:**
- **Stakeholder Satisfaction:** [AI_SYNTHESIS: Stakeholder satisfaction with engagement process, outcomes, and value delivery]
- **Relationship Quality:** [AI_SYNTHESIS: Quality of relationships, trust levels, and collaborative effectiveness]
- **Influence Alignment:** [AI_SYNTHESIS: Alignment of stakeholder influence with project objectives and success criteria]

### Monitoring and Reporting Framework
**Regular Monitoring:**
- **Engagement Dashboard:** [AI_SYNTHESIS: Comprehensive dashboard for tracking engagement metrics, status, and trends]
- **Stakeholder Pulse Checks:** [AI_SYNTHESIS: Regular pulse checks on stakeholder satisfaction, engagement, and concerns]
- **Issue Tracking:** [AI_SYNTHESIS: Systematic tracking of engagement issues, resolution status, and improvement actions]

**Reporting Schedule:**
- **Weekly Reports:** [AI_SYNTHESIS: Weekly engagement status reports for project team and immediate stakeholders]
- **Monthly Reports:** [AI_SYNTHESIS: Monthly comprehensive engagement reports for sponsors and key stakeholders]
- **Quarterly Reviews:** [AI_SYNTHESIS: Quarterly comprehensive engagement plan reviews, updates, and strategic adjustments]

---

## 7. Risk Management and Mitigation

### Engagement Risk Assessment
**High-Risk Scenarios:**
- **Sponsor Disengagement:** [AI_SYNTHESIS: Risk of sponsor losing interest, confidence, or support for the project]
- **Stakeholder Resistance:** [AI_SYNTHESIS: Risk of stakeholder resistance to project changes or implementation]
- **Communication Breakdown:** [AI_SYNTHESIS: Risk of communication failures, misunderstandings, or information gaps]

**Medium-Risk Scenarios:**
- **Competing Priorities:** [AI_SYNTHESIS: Risk of stakeholders having competing priorities or resource constraints]
- **Resource Constraints:** [AI_SYNTHESIS: Risk of insufficient resources for effective engagement and participation]
- **Change Fatigue:** [AI_SYNTHESIS: Risk of stakeholder fatigue from organizational changes or project demands]

### Mitigation Strategies
**Proactive Mitigation:**
- **Early Engagement:** [AI_SYNTHESIS: Early and comprehensive stakeholder engagement to build support and understanding]
- **Clear Communication:** [AI_SYNTHESIS: Clear, consistent communication to prevent misunderstandings and build trust]
- **Value Demonstration:** [AI_SYNTHESIS: Regular demonstration of project value, benefits, and positive outcomes]

**Reactive Mitigation:**
- **Issue Escalation:** [AI_SYNTHESIS: Clear escalation paths for addressing engagement issues and conflicts]
- **Conflict Resolution:** [AI_SYNTHESIS: Structured processes for resolving stakeholder conflicts and concerns]
- **Recovery Planning:** [AI_SYNTHESIS: Comprehensive plans for recovering from engagement setbacks or failures]

---

## Conclusion and Next Steps

**Engagement Plan Summary:**  
[AI_SYNTHESIS: Comprehensive summary of the key elements, objectives, and strategies of the engagement plan]

**Critical Success Factors:**  
[AI_SYNTHESIS: The most critical factors for successful stakeholder engagement and project authorization]

**Immediate Actions Required:**  
[AI_SYNTHESIS: Immediate actions needed to begin implementing the engagement plan effectively]

**Long-term Vision:**  
[AI_SYNTHESIS: Long-term vision for stakeholder relationship management and engagement excellence]

---

*This Stakeholder Engagement Plan provides a comprehensive framework for ensuring clear project charter understanding, confident sponsor authorization, and effective stakeholder participation throughout the project lifecycle.*`;
  }
}
