import { ProjectContext } from '../../types';

/**
 * RequirementsAnalysisAndDesignDefinitionTemplate generates the structure and default content for the BABOK Requirements Analysis & Design Definition document.
 */
export class RequirementsAnalysisAndDesignDefinitionTemplate {
  /**
   * Generate the default content for the Requirements Analysis & Design Definition document.
   * @param context ProjectContext for dynamic content (if needed)
   */
  generateContent(context: ProjectContext): string {
    return `# Requirements Analysis & Design Definition

**Category:** BABOK

## Purpose
Describes the tasks and techniques used to structure, specify, and validate requirements and designs, ensuring solutions meet business needs and stakeholder expectations.

## Key Activities
- Specify and model requirements
- Verify and validate requirements
- Define solution options
- Analyze potential value and recommend solutions

## Checklist
- [ ] Requirements specified and modeled
- [ ] Requirements verified and validated
- [ ] Solution options defined
- [ ] Value analysis and recommendations completed

## Summary
Requirements Analysis & Design Definition ensures that business, stakeholder, and solution requirements are clearly defined, validated, and aligned with organizational goals. It supports the development of effective, value-driven solutions.

## Revision History
- ${new Date().toISOString().slice(0, 10)}: Initial version generated by ADPA Document Generator.
`;
  }
}
