import type { ProjectContext } from '../../../index.js';

/**
 * SolutionEvaluationTemplate
 * Template for BABOK Solution Evaluation document.
 * Provides structure and default content for the document.
 */
export class SolutionEvaluationTemplate {
  /**
   * Generate the default content for the Solution Evaluation document.
   * @param context ProjectContext for dynamic content population
   * @returns Markdown string for the document
   */
  generateContent(context: ProjectContext): string {
    return `# Solution Evaluation

**Category:** BABOK

## Purpose
Describes the tasks and techniques used to assess the performance and value delivered by a solution, and to recommend improvements.

## Key Activities
- Measure solution performance
- Analyze performance results
- Assess limitations
- Recommend actions to increase value

## Solution Performance Assessment
- Define evaluation criteria and metrics
- Collect and analyze performance data
- Identify gaps between expected and actual results

## Limitations and Risks
- Document any limitations, constraints, or risks identified during evaluation
- Assess their impact on stakeholders and business objectives

## Recommendations
- Provide actionable recommendations for improvement or remediation
- Prioritize recommendations based on impact and feasibility

## Stakeholder Feedback
- Summarize feedback from key stakeholders
- Note any concerns or suggestions for future consideration

## Summary
Solution Evaluation ensures that the implemented solution meets business needs and delivers value. Ongoing evaluation and feedback drive continuous improvement.

## Revision History
- ${new Date().toISOString().slice(0, 10)}: Initial version generated by ADPA Document Generator.
`;
  }
}
