import type { ProjectContext } from '../../ai/types';

/**
 * Assumptions Log Template for Project Charter
 * 
 * This template provides a comprehensive structure for documenting, tracking, and managing
 * project assumptions throughout the project lifecycle. It serves as a living document
 * that supports risk management and decision-making processes.
 */
export class AssumptionsLogTemplate {
  constructor(private context: ProjectContext) {}

  /**
   * Generate comprehensive Assumptions Log content with tracking and validation framework
   */
  generateContent(): string {
    const projectName = this.context.projectName || 'Project';
    const projectType = this.context.projectType || 'Strategic Initiative';
    
    return `# Assumptions Log - ${projectName}

**Generated by Requirements Gathering Agent v2.1.3**  
**Category:** project-charter  
**Generated:** ${new Date().toISOString()}  
**Description:** Comprehensive Project Assumptions Log with Tracking Framework

---

## 🎯 **ASSUMPTIONS LOG PURPOSE**

This Assumptions Log serves as the central repository for documenting, tracking, and validating all project assumptions throughout the project lifecycle. It supports informed decision-making, risk management, and stakeholder communication by maintaining transparency about the foundational beliefs underlying project planning and execution.

**PMBOK Reference:** 4.1.3.2 - Assumptions Log (Project Charter Component)

---

## 📋 **DOCUMENT OVERVIEW**

**Project Title:** ${projectName}  
**Project Type:** ${projectType}  
**Log Creation Date:** ${new Date().toISOString().split('T')[0]}  
**Document Owner:** Project Manager  
**Review Frequency:** [Weekly/Bi-weekly/Monthly]  
**Last Updated:** ${new Date().toISOString().split('T')[0]}  
**Version:** 1.0

---

## 🔍 **AI SYNTHESIS INSTRUCTIONS**

**MISSION**: As a Project Manager with comprehensive knowledge of project management best practices, synthesize ALL foundational documents to identify, categorize, and document critical project assumptions that underpin project planning and execution.

**REQUIRED SYNTHESIS SOURCES**:
1. **Business Case** → Extract business and financial assumptions
2. **Stakeholder Register** → Identify stakeholder availability and engagement assumptions  
3. **Scope Statement** → Extract technical and delivery assumptions
4. **Risk Register** → Identify assumptions that could become risks if proven false
5. **Project Context** → Infer environmental and organizational assumptions

**SYNTHESIS APPROACH**:
- **Comprehensive Identification**: Extract both explicit and implicit assumptions from all documents
- **Risk-Based Categorization**: Classify assumptions by their potential impact if proven false
- **Validation Framework**: Establish methods for testing and validating each assumption
- **Tracking Mechanism**: Create a system for monitoring assumption validity throughout the project
- **Impact Assessment**: Evaluate the consequences of assumption changes on project success

---

## 1. Assumptions Management Framework

### 1.1 Assumption Categories

**Strategic Assumptions**: High-level business and organizational assumptions  
**Technical Assumptions**: Technology, system, and implementation assumptions  
**Resource Assumptions**: Personnel, budget, and capability assumptions  
**Environmental Assumptions**: External factors and organizational context assumptions  
**Stakeholder Assumptions**: Stakeholder behavior and engagement assumptions

### 1.2 Assumption Status Definitions

- **Active**: Assumption is currently valid and being monitored
- **Validated**: Assumption has been confirmed through evidence or testing
- **Invalid**: Assumption has been proven false and requires response
- **Under Review**: Assumption validity is being investigated
- **Retired**: Assumption is no longer relevant to the project

### 1.3 Impact Classification

- **Critical**: Assumption failure would significantly impact project success
- **High**: Assumption failure would cause major adjustments to scope, schedule, or budget
- **Medium**: Assumption failure would require moderate project adjustments
- **Low**: Assumption failure would have minimal project impact

---

## 2. Strategic and Business Assumptions

### 2.1 Business Environment Assumptions
[AI_SYNTHESIS: Extract business environment assumptions from the Business Case, including market conditions, organizational priorities, and strategic context that underpin the project rationale]

| ID | Assumption | Source | Impact | Status | Validation Method | Owner | Review Date |
|----|------------|--------|--------|--------|-------------------|-------|-------------|
| SA-001 | [AI: Business assumption 1] | Business Case | Critical | Active | [Validation approach] | [Owner] | [Date] |
| SA-002 | [AI: Business assumption 2] | Business Case | High | Active | [Validation approach] | [Owner] | [Date] |

### 2.2 Financial and Budget Assumptions
[AI_SYNTHESIS: Identify financial assumptions from the Business Case including budget availability, cost estimates, ROI calculations, and funding continuity]

| ID | Assumption | Source | Impact | Status | Validation Method | Owner | Review Date |
|----|------------|--------|--------|--------|-------------------|-------|-------------|
| FA-001 | [AI: Financial assumption 1] | Business Case | Critical | Active | [Validation approach] | [Owner] | [Date] |
| FA-002 | [AI: Financial assumption 2] | Business Case | High | Active | [Validation approach] | [Owner] | [Date] |

### 2.3 Organizational Assumptions
[AI_SYNTHESIS: Extract organizational assumptions including change readiness, resource availability, decision-making processes, and organizational support]

| ID | Assumption | Source | Impact | Status | Validation Method | Owner | Review Date |
|----|------------|--------|--------|--------|-------------------|-------|-------------|
| OA-001 | [AI: Organizational assumption 1] | Stakeholder Register | High | Active | [Validation approach] | [Owner] | [Date] |
| OA-002 | [AI: Organizational assumption 2] | Stakeholder Register | Medium | Active | [Validation approach] | [Owner] | [Date] |

---

## 3. Technical and Implementation Assumptions

### 3.1 Technology Assumptions
[AI_SYNTHESIS: Identify technical assumptions from the Scope Statement and project context including technology capabilities, system compatibility, performance expectations, and technical constraints]

| ID | Assumption | Source | Impact | Status | Validation Method | Owner | Review Date |
|----|------------|--------|--------|--------|-------------------|-------|-------------|
| TA-001 | [AI: Technology assumption 1] | Scope Statement | Critical | Active | [Validation approach] | [Owner] | [Date] |
| TA-002 | [AI: Technology assumption 2] | Project Context | High | Active | [Validation approach] | [Owner] | [Date] |

### 3.2 Integration and Compatibility Assumptions
[AI_SYNTHESIS: Extract assumptions about system integrations, data compatibility, interface requirements, and technical dependencies]

| ID | Assumption | Source | Impact | Status | Validation Method | Owner | Review Date |
|----|------------|--------|--------|--------|-------------------|-------|-------------|
| IA-001 | [AI: Integration assumption 1] | Scope Statement | High | Active | [Validation approach] | [Owner] | [Date] |
| IA-002 | [AI: Integration assumption 2] | Technical Context | Medium | Active | [Validation approach] | [Owner] | [Date] |

### 3.3 Performance and Quality Assumptions
[AI_SYNTHESIS: Identify assumptions about system performance, quality standards, user acceptance criteria, and operational requirements]

| ID | Assumption | Source | Impact | Status | Validation Method | Owner | Review Date |
|----|------------|--------|--------|--------|-------------------|-------|-------------|
| PA-001 | [AI: Performance assumption 1] | Scope Statement | High | Active | [Validation approach] | [Owner] | [Date] |
| PA-002 | [AI: Performance assumption 2] | Requirements | Medium | Active | [Validation approach] | [Owner] | [Date] |

---

## 4. Resource and Capability Assumptions

### 4.1 Human Resource Assumptions
[AI_SYNTHESIS: Extract assumptions about team member availability, skill levels, experience, and capacity from the Stakeholder Register and project context]

| ID | Assumption | Source | Impact | Status | Validation Method | Owner | Review Date |
|----|------------|--------|--------|--------|-------------------|-------|-------------|
| RA-001 | [AI: Resource assumption 1] | Stakeholder Register | Critical | Active | [Validation approach] | [Owner] | [Date] |
| RA-002 | [AI: Resource assumption 2] | Project Context | High | Active | [Validation approach] | [Owner] | [Date] |

### 4.2 Skill and Expertise Assumptions
[AI_SYNTHESIS: Identify assumptions about required skills, training needs, knowledge transfer, and expertise availability]

| ID | Assumption | Source | Impact | Status | Validation Method | Owner | Review Date |
|----|------------|--------|--------|--------|-------------------|-------|-------------|
| SKA-001 | [AI: Skill assumption 1] | Resource Planning | High | Active | [Validation approach] | [Owner] | [Date] |
| SKA-002 | [AI: Skill assumption 2] | Team Assessment | Medium | Active | [Validation approach] | [Owner] | [Date] |

### 4.3 External Resource Assumptions
[AI_SYNTHESIS: Extract assumptions about vendor capabilities, third-party services, external dependencies, and supplier performance]

| ID | Assumption | Source | Impact | Status | Validation Method | Owner | Review Date |
|----|------------|--------|--------|--------|-------------------|-------|-------------|
| ERA-001 | [AI: External resource assumption 1] | Vendor Assessment | High | Active | [Validation approach] | [Owner] | [Date] |
| ERA-002 | [AI: External resource assumption 2] | Procurement Plan | Medium | Active | [Validation approach] | [Owner] | [Date] |

---

## 5. Stakeholder and Communication Assumptions

### 5.1 Stakeholder Engagement Assumptions
[AI_SYNTHESIS: Extract stakeholder assumptions from the Stakeholder Register including availability, engagement levels, decision-making authority, and communication preferences]

| ID | Assumption | Source | Impact | Status | Validation Method | Owner | Review Date |
|----|------------|--------|--------|--------|-------------------|-------|-------------|
| SEA-001 | [AI: Stakeholder engagement assumption 1] | Stakeholder Register | Critical | Active | [Validation approach] | [Owner] | [Date] |
| SEA-002 | [AI: Stakeholder engagement assumption 2] | Communication Plan | High | Active | [Validation approach] | [Owner] | [Date] |

### 5.2 Decision-Making Assumptions
[AI_SYNTHESIS: Identify assumptions about decision-making processes, approval authorities, escalation procedures, and governance structures]

| ID | Assumption | Source | Impact | Status | Validation Method | Owner | Review Date |
|----|------------|--------|--------|--------|-------------------|-------|-------------|
| DMA-001 | [AI: Decision-making assumption 1] | Governance Framework | Critical | Active | [Validation approach] | [Owner] | [Date] |
| DMA-002 | [AI: Decision-making assumption 2] | Authority Matrix | High | Active | [Validation approach] | [Owner] | [Date] |

---

## 6. Environmental and External Assumptions

### 6.1 Market and Industry Assumptions
[AI_SYNTHESIS: Extract external environment assumptions including market conditions, industry trends, regulatory environment, and competitive landscape]

| ID | Assumption | Source | Impact | Status | Validation Method | Owner | Review Date |
|----|------------|--------|--------|--------|-------------------|-------|-------------|
| MIA-001 | [AI: Market assumption 1] | Business Case | High | Active | [Validation approach] | [Owner] | [Date] |
| MIA-002 | [AI: Market assumption 2] | Industry Analysis | Medium | Active | [Validation approach] | [Owner] | [Date] |

### 6.2 Regulatory and Compliance Assumptions
[AI_SYNTHESIS: Identify assumptions about regulatory requirements, compliance standards, legal constraints, and policy changes]

| ID | Assumption | Source | Impact | Status | Validation Method | Owner | Review Date |
|----|------------|--------|--------|--------|-------------------|-------|-------------|
| RCA-001 | [AI: Regulatory assumption 1] | Compliance Assessment | Critical | Active | [Validation approach] | [Owner] | [Date] |
| RCA-002 | [AI: Regulatory assumption 2] | Legal Review | High | Active | [Validation approach] | [Owner] | [Date] |

---

## 7. Schedule and Timeline Assumptions

### 7.1 Project Timeline Assumptions
[AI_SYNTHESIS: Extract timeline assumptions including project duration, milestone dates, dependency timing, and schedule constraints]

| ID | Assumption | Source | Impact | Status | Validation Method | Owner | Review Date |
|----|------------|--------|--------|--------|-------------------|-------|-------------|
| PTA-001 | [AI: Timeline assumption 1] | Project Schedule | Critical | Active | [Validation approach] | [Owner] | [Date] |
| PTA-002 | [AI: Timeline assumption 2] | Milestone Planning | High | Active | [Validation approach] | [Owner] | [Date] |

### 7.2 Dependency and Sequencing Assumptions
[AI_SYNTHESIS: Identify assumptions about task dependencies, work sequencing, parallel activities, and critical path elements]

| ID | Assumption | Source | Impact | Status | Validation Method | Owner | Review Date |
|----|------------|--------|--------|--------|-------------------|-------|-------------|
| DSA-001 | [AI: Dependency assumption 1] | Work Breakdown | High | Active | [Validation approach] | [Owner] | [Date] |
| DSA-002 | [AI: Dependency assumption 2] | Critical Path | Medium | Active | [Validation approach] | [Owner] | [Date] |

---

## 8. Risk-Related Assumptions

### 8.1 Risk Probability Assumptions
[AI_SYNTHESIS: Extract risk-related assumptions from the Risk Register including probability estimates, impact assessments, and risk tolerance levels]

| ID | Assumption | Source | Impact | Status | Validation Method | Owner | Review Date |
|----|------------|--------|--------|--------|-------------------|-------|-------------|
| RPA-001 | [AI: Risk probability assumption 1] | Risk Register | Critical | Active | [Validation approach] | [Owner] | [Date] |
| RPA-002 | [AI: Risk probability assumption 2] | Risk Assessment | High | Active | [Validation approach] | [Owner] | [Date] |

### 8.2 Mitigation Effectiveness Assumptions
[AI_SYNTHESIS: Identify assumptions about risk mitigation strategies, contingency plan effectiveness, and response capabilities]

| ID | Assumption | Source | Impact | Status | Validation Method | Owner | Review Date |
|----|------------|--------|--------|--------|-------------------|-------|-------------|
| MEA-001 | [AI: Mitigation assumption 1] | Risk Response Plan | High | Active | [Validation approach] | [Owner] | [Date] |
| MEA-002 | [AI: Mitigation assumption 2] | Contingency Planning | Medium | Active | [Validation approach] | [Owner] | [Date] |

---

## 9. Assumption Validation and Monitoring

### 9.1 Validation Schedule

| Assumption Category | Validation Frequency | Validation Method | Responsible Party |
|-------------------|---------------------|-------------------|-------------------|
| Strategic Assumptions | Monthly | Executive Review | Project Sponsor |
| Technical Assumptions | Bi-weekly | Technical Assessment | Technical Lead |
| Resource Assumptions | Weekly | Resource Review | Resource Manager |
| Stakeholder Assumptions | Bi-weekly | Stakeholder Check-in | Project Manager |
| Environmental Assumptions | Monthly | Environmental Scan | Business Analyst |

### 9.2 Assumption Change Impact Assessment

**Process for Assumption Changes:**
1. **Identification**: Document when an assumption is challenged or proven false
2. **Impact Analysis**: Assess the impact on scope, schedule, budget, and quality
3. **Response Planning**: Develop response strategies for assumption changes
4. **Stakeholder Communication**: Notify affected stakeholders of assumption changes
5. **Plan Updates**: Update project plans to reflect assumption changes

### 9.3 Escalation Criteria

**Immediate Escalation Required When:**
- Critical assumptions are proven false
- Multiple related assumptions become invalid
- Assumption changes threaten project viability
- Assumption validation reveals significant new risks

---

## 10. Assumption Log Maintenance

### 10.1 Update Procedures

**Regular Updates:**
- Weekly review of active assumptions
- Monthly validation of critical assumptions
- Quarterly comprehensive assumption review
- Ad-hoc updates when new information becomes available

**Documentation Requirements:**
- All assumption changes must be documented with rationale
- Validation evidence must be maintained for audit purposes
- Impact assessments must be completed for all assumption changes
- Stakeholder notifications must be tracked and confirmed

### 10.2 Version Control

**Version History:**
| Version | Date | Changes | Updated By |
|---------|------|---------|------------|
| 1.0 | ${new Date().toISOString().split('T')[0]} | Initial creation | Project Manager |

### 10.3 Integration with Project Management

**Related Documents:**
- Project Charter (parent document)
- Risk Register (assumption-risk relationship)
- Issue Log (assumption validation issues)
- Change Request Log (assumption-driven changes)
- Stakeholder Register (assumption ownership)

---

## 11. Assumption Log Summary

### 11.1 Assumption Statistics

**Total Assumptions:** [AI_SYNTHESIS: Count total assumptions identified]  
**Critical Assumptions:** [AI_SYNTHESIS: Count critical impact assumptions]  
**Active Assumptions:** [AI_SYNTHESIS: Count currently active assumptions]  
**Validated Assumptions:** [AI_SYNTHESIS: Count validated assumptions]  
**Assumptions Under Review:** [AI_SYNTHESIS: Count assumptions being reviewed]

### 11.2 Key Assumption Themes

[AI_SYNTHESIS: Identify the main themes or patterns in the project assumptions, highlighting areas of highest uncertainty or risk]

### 11.3 Recommendation for Assumption Management

[AI_SYNTHESIS: Provide specific recommendations for managing the identified assumptions, including priority areas for validation and monitoring]

---

## 12. Appendices

### Appendix A: Assumption Validation Templates
[Templates for documenting assumption validation activities]

### Appendix B: Assumption Change Request Form
[Form for requesting changes to documented assumptions]

### Appendix C: Assumption Risk Assessment Matrix
[Matrix for assessing the risk impact of assumption changes]

---

*This Assumptions Log was generated through comprehensive synthesis of foundational project documents including the Business Case, Stakeholder Register, Scope Statement, and Risk Register. It serves as a living document that should be regularly updated and validated throughout the project lifecycle.*

**Document Control:**
- **Next Review Date:** [Schedule based on project phase]
- **Distribution List:** Project Team, Stakeholders, PMO
- **Storage Location:** Project Repository
- **Access Level:** Project Team and Stakeholders

---

**Note:** This assumptions log should be reviewed and updated regularly as part of project governance activities. All assumption changes should be communicated to relevant stakeholders and reflected in related project documents.`;
  }
}