import type { ProjectContext } from '../../ai/types';

/**
 * Ultimate Project Charter Template with Executive Authority
 * 
 * This template provides the authoritative structure for PMBOK-compliant Project Charter 
 * generation, designed for synthesis across all foundational documents by a PMO Director
 * and Executive Sponsor persona with full organizational authority.
 */
export class ProjectcharterTemplate {
  constructor(private context: ProjectContext) {}

  /**
   * Generate comprehensive Project Charter content with executive synthesis instructions
   */
  generateContent(): string {
    const projectName = this.context.projectName || 'Project';
    const projectType = this.context.projectType || 'Strategic Initiative';
    
    return `# Project Charter

**Generated by Requirements Gathering Agent v2.1.3**  
**Category:** project-charter  
**Generated:** ${new Date().toISOString()}  
**Description:** Executive Project Charter with Full Organizational Authority

---

## 🎯 **EXECUTIVE SYNTHESIS INSTRUCTIONS**

**MISSION**: As PMO Director and Executive Sponsor, synthesize ALL foundational documents into an authoritative Project Charter that formally establishes project legitimacy and grants full organizational authority to the Project Manager.

**REQUIRED SYNTHESIS SOURCES**:
1. **Business Case** → Extract strategic justification, ROI, and business objectives
2. **Stakeholder Register** → Identify key decision makers, sponsors, and authority structure  
3. **Scope Statement** → Define high-level deliverables, boundaries, and success criteria
4. **Risk Register** → Summarize critical risks requiring executive attention and mitigation approval

**SYNTHESIS APPROACH**:
- **Strategic Authority**: Write from the perspective of someone committing organizational resources
- **Executive Summary**: Distill complex analysis into executive-digestible insights
- **Decision Documentation**: Record all key decisions and assumptions for future reference
- **Resource Authorization**: Explicitly grant authority for budget, personnel, and organizational assets
- **Governance Framework**: Establish reporting relationships and decision-making protocols

---

# Project Charter - ${projectName}

**Project Title:** ${projectName}  
**Project Type:** ${projectType}  
**Charter Date:** ${new Date().toISOString().split('T')[0]}  
**Project Manager:** [TO BE ASSIGNED]  
**Executive Sponsor:** [EXECUTIVE SPONSOR NAME]  
**PMO Director:** [PMO DIRECTOR NAME]

---

## 1. Executive Summary

**Strategic Context:**  
[AI_SYNTHESIS: Extract and synthesize the strategic business rationale from the Business Case, explaining why this project is critical to organizational success and how it aligns with corporate strategy]

**Business Justification:**  
[AI_SYNTHESIS: Synthesize the financial and strategic justification from the Business Case, including ROI projections, cost-benefit analysis, and strategic value proposition]

**Authority and Approval:**  
This Project Charter formally authorizes the initiation of ${projectName} and grants the designated Project Manager full authority to commit organizational resources within the approved parameters outlined in this document.

---

## 2. Project Objectives and Success Criteria

### Primary Objectives
[AI_SYNTHESIS: Extract and prioritize the top 3-5 strategic objectives from the Business Case and Scope Statement, ensuring they are measurable and aligned with organizational goals]

### Success Criteria
[AI_SYNTHESIS: Synthesize specific, measurable success criteria from the Scope Statement and Business Case, including both quantitative metrics and qualitative outcomes]

### Key Performance Indicators (KPIs)
[AI_SYNTHESIS: Define measurable KPIs that will be used to track project success and ROI achievement throughout the project lifecycle]

---

## 3. Project Scope and Deliverables

### High-Level Scope
[AI_SYNTHESIS: Synthesize the high-level project scope from the Scope Statement, focusing on the strategic deliverables and outcomes that matter to executive stakeholders]

### Major Deliverables
[AI_SYNTHESIS: Extract and list the major deliverables from the Scope Statement that represent significant value delivery milestones for the organization]

### Scope Boundaries
**In Scope:**  
[AI_SYNTHESIS: Summarize the key items that are explicitly included in project scope, focusing on those with significant resource or strategic implications]

**Out of Scope:**  
[AI_SYNTHESIS: Summarize the key items that are explicitly excluded from project scope, particularly those that might be expected by stakeholders but are not included]

---

## 4. Stakeholder Authority and Governance

### Executive Stakeholders
[AI_SYNTHESIS: Extract and synthesize the high-power, high-interest stakeholders from the Stakeholder Register who have decision-making authority or significant influence over project success]

### Governance Structure
[AI_SYNTHESIS: Based on the Stakeholder Register, define the project governance structure including reporting relationships, decision-making protocols, and escalation procedures]

### Communication and Engagement Strategy
[AI_SYNTHESIS: Synthesize the key communication requirements and engagement strategies for executive and high-influence stakeholders from the Stakeholder Register]

---

## 5. Resource Authorization and Budget

### Budget Authorization
**Total Project Budget:** [AI_SYNTHESIS: Extract budget information from Business Case or indicate where detailed budget planning will occur]

**Budget Authority:** The Project Manager is authorized to commit resources up to the approved project budget with appropriate approval workflows for expenditures exceeding [THRESHOLD] per the organization's financial policies.

### Resource Allocation
[AI_SYNTHESIS: Based on project scope and stakeholder analysis, identify the types and levels of resources (personnel, technology, facilities) that the Project Manager is authorized to engage]

### Organizational Support
This charter authorizes the Project Manager to request and receive appropriate organizational support, including access to subject matter experts, organizational data, and cross-functional collaboration as needed for project success.

---

## 6. Risk Management and Mitigation Authority

### Critical Risk Summary
[AI_SYNTHESIS: Extract and synthesize the top 5-7 highest-impact risks from the Risk Register that require executive awareness and potential escalation]

### Risk Management Authority
The Project Manager is authorized to implement approved risk mitigation strategies and escalate risks exceeding the defined thresholds to the Executive Sponsor for additional resource allocation or strategic decision-making.

### Contingency Authorization
[AI_SYNTHESIS: Based on the Risk Register, identify what contingency resources or authority the Project Manager has to respond to identified risks]

---

## 7. Project Timeline and Milestones

### High-Level Timeline
[AI_SYNTHESIS: Based on scope and complexity indicators from all foundational documents, provide realistic high-level timeline estimates for major project phases]

### Key Milestones
[AI_SYNTHESIS: Define strategic milestones that represent significant value delivery or decision points requiring executive review]

### Critical Dependencies
[AI_SYNTHESIS: Identify any critical external dependencies or organizational constraints that could impact timeline achievement]

---

## 8. Assumptions and Constraints

### Key Assumptions
[AI_SYNTHESIS: Synthesize critical assumptions from all foundational documents that underpin the project approach and resource requirements]

### Organizational Constraints
[AI_SYNTHESIS: Identify any organizational, technical, or resource constraints from the foundational documents that impact project execution]

### External Dependencies
[AI_SYNTHESIS: Identify any external dependencies or factors beyond project control that could impact success]

---

## 9. Project Manager Authority and Responsibilities

### Authority Granted
The designated Project Manager is hereby granted authority to:
- Commit organizational resources within the approved project budget
- Make day-to-day project decisions within the defined scope
- Engage cross-functional teams and subject matter experts as needed
- Implement approved risk mitigation strategies
- Represent the project in organizational forums and stakeholder communications

### Key Responsibilities
- Deliver project objectives within scope, schedule, and budget parameters
- Maintain regular communication with Executive Sponsor and key stakeholders
- Manage project risks and escalate issues beyond defined thresholds
- Ensure project deliverables meet quality standards and acceptance criteria
- Provide regular status reporting per the established governance framework

### Escalation Protocols
[AI_SYNTHESIS: Define clear escalation paths for decisions or issues that exceed the Project Manager's authority, based on the stakeholder governance structure]

---

## 10. Approval and Authorization

### Executive Approval
By signing below, the Executive Sponsor formally authorizes the initiation of ${projectName} and commits the organization to provide the necessary resources and support for project success.

**Executive Sponsor:** _____________________________ **Date:** __________  
**Signature:** _____________________________

**PMO Director:** _____________________________ **Date:** __________  
**Signature:** _____________________________

### Project Manager Acceptance
By signing below, the designated Project Manager accepts responsibility for delivering the project objectives within the parameters defined in this charter.

**Project Manager:** _____________________________ **Date:** __________  
**Signature:** _____________________________

---

## 11. Charter Change Control

Any changes to this Project Charter must be approved by the Executive Sponsor and documented through the organization's formal change control process. Significant scope, budget, or timeline changes may require additional executive approval per organizational governance policies.

**Charter Version:** 1.0  
**Last Updated:** ${new Date().toISOString()}  
**Next Review:** [Schedule based on project phase]

---

*This Project Charter was generated through comprehensive synthesis of foundational project documents including the Business Case, Stakeholder Register, Scope Statement, and Risk Register. It represents the formal authorization and organizational commitment for project execution.*`;
  }
}
