import type { ProjectContext } from '../../ai/types';

/**
 * Enhanced Risk Register Template with intelligent risk identification and structured analysis
 * 
 * This template provides a comprehensive PMBOK-compliant risk register that combines:
 * - AI-inferred project risks from context analysis
 * - Structured risk assessment matrices
 * - Professional risk response strategies
 * - Educational guidance for risk management best practices
 */
export class RiskregisterTemplate {
  constructor(private context: ProjectContext) {}

  /**
   * Generate comprehensive Risk Register content with intelligent risk synthesis
   */
  generateContent(): string {
    const projectName = this.context.projectName || 'Project';
    const projectType = this.context.projectType || 'Software Development';
    
    return `# Risk Register

**Generated by Requirements Gathering Agent v2.1.3**  
**Category:** risk-management  
**Generated:** ${new Date().toISOString()}  
**Description:** PMBOK-compliant Risk Register with intelligent risk identification

---

## 🎯 **AI INSTRUCTIONS FOR ENHANCED RISK IDENTIFICATION**

**SYNTHESIS TASK**: Analyze the following project documents and context to identify comprehensive project risks:

1. **Project README/Context**: Extract technical, operational, and strategic risks
2. **Business Case**: Identify financial, market, and business risks  
3. **Scope Statement**: Identify scope, requirement, and delivery risks
4. **Stakeholder Register**: Identify stakeholder, communication, and political risks
5. **Project Type (${projectType})**: Apply domain-specific risk patterns

**RISK IDENTIFICATION FRAMEWORK**:
- **Technical Risks**: Dependencies, integrations, performance, security
- **Operational Risks**: Resources, skills, processes, timelines  
- **External Risks**: Market, regulatory, vendor, environmental
- **Organizational Risks**: Stakeholder, change management, governance
- **Financial Risks**: Budget, cost overruns, ROI, funding

**OUTPUT REQUIREMENTS**: 
- Populate ALL risk tables with project-specific risks (minimum 10-15 risks)
- Provide realistic probability/impact assessments
- Include concrete, actionable mitigation strategies
- Replace ALL placeholder text with intelligent analysis

---

# Risk Register - ${projectName}

**Project:** ${projectName}  
**Project Type:** ${projectType}  
**PMBOK Reference:** 11.2.3.1 (Risk Register)  
**Document Version:** 1.0  

---

## Document Purpose

This Risk Register identifies, analyzes, and documents all project risks that could impact project objectives. It serves as the central repository for risk information and provides the foundation for risk response planning and monitoring throughout the project lifecycle.

---

## 1. Risk Management Summary

### Risk Assessment Scale

**Probability Scale:**  
- **Very Low (1)**: 1-10% chance of occurrence
- **Low (2)**: 11-30% chance of occurrence  
- **Medium (3)**: 31-50% chance of occurrence
- **High (4)**: 51-70% chance of occurrence
- **Very High (5)**: 71-90% chance of occurrence

**Impact Scale:**  
- **Very Low (1)**: Minimal impact on project objectives
- **Low (2)**: Minor impact, easily manageable
- **Medium (3)**: Moderate impact, requires attention  
- **High (4)**: Significant impact, major management required
- **Very High (5)**: Severe impact, project success threatened

**Risk Score = Probability × Impact**  
- **1-5**: Low Risk (Monitor)
- **6-10**: Medium Risk (Manage)  
- **11-15**: High Risk (Immediate Action)
- **16-25**: Critical Risk (Escalate)

---

## 2. Project Risk Register

### High-Priority Risks (Score: 11-25)

| Risk ID | Risk Description | Category | Probability | Impact | Risk Score | Risk Owner | Mitigation Strategy | Status |
|---------|------------------|----------|-------------|--------|------------|------------|---------------------|--------|
| [AI_TO_POPULATE] | [AI: Identify highest-probability, high-impact risks from project context] | [AI: Technical/Operational/External/Organizational/Financial] | [AI: 1-5] | [AI: 1-5] | [AI: Calculate] | [AI: Suggest appropriate owner] | [AI: Concrete mitigation actions] | Open |

### Medium-Priority Risks (Score: 6-10)

| Risk ID | Risk Description | Category | Probability | Impact | Risk Score | Risk Owner | Mitigation Strategy | Status |
|---------|------------------|----------|-------------|--------|------------|------------|---------------------|--------|
| [AI_TO_POPULATE] | [AI: Identify moderate risks that require management attention] | [AI: Category] | [AI: 1-5] | [AI: 1-5] | [AI: Calculate] | [AI: Owner] | [AI: Strategy] | Open |

### Low-Priority Risks (Score: 1-5)

| Risk ID | Risk Description | Category | Probability | Impact | Risk Score | Risk Owner | Mitigation Strategy | Status |
|---------|------------------|----------|-------------|--------|------------|------------|---------------------|--------|
| [AI_TO_POPULATE] | [AI: Identify lower-probability or low-impact risks for monitoring] | [AI: Category] | [AI: 1-5] | [AI: 1-5] | [AI: Calculate] | [AI: Owner] | [AI: Strategy] | Open |

---

## 3. Risk Category Analysis

### Technical Risks
[AI: Analyze technical dependencies, integration points, performance requirements, security concerns, and technology risks specific to this project]

### Operational Risks  
[AI: Analyze resource availability, skill gaps, process dependencies, timeline constraints, and operational challenges]

### External Risks
[AI: Analyze market conditions, regulatory requirements, vendor dependencies, and environmental factors]

### Organizational Risks
[AI: Analyze stakeholder dynamics, change management challenges, governance issues, and organizational capacity]

### Financial Risks
[AI: Analyze budget constraints, cost overrun potential, funding risks, and financial impact scenarios]

---

## 4. Risk Response Strategies

### Risk Response Types (PMBOK Framework)

**Avoid**: Eliminate the threat by changing project approach  
**Mitigate**: Reduce probability or impact of the risk  
**Transfer**: Shift risk responsibility to third party  
**Accept**: Acknowledge risk and plan contingency response  

### Contingency Plans

| Risk ID | Trigger Events | Contingency Response | Resources Required | Timeline |
|---------|---------------|---------------------|-------------------|----------|
| [AI_TO_POPULATE] | [AI: Specific conditions that trigger response] | [AI: Detailed response actions] | [AI: Required resources] | [AI: Response timeline] |

---

## 5. Risk Monitoring and Control

### Risk Review Schedule
- **Weekly Risk Reviews**: Project team assessment of active risks
- **Monthly Risk Reports**: Stakeholder communication and risk status updates  
- **Quarterly Risk Audits**: Comprehensive risk register review and updates

### Key Risk Indicators (KRIs)
[AI: Define 3-5 measurable indicators that signal increasing risk exposure for this specific project]

### Escalation Criteria
- **Medium Risk (6-10)**: Escalate to Project Manager
- **High Risk (11-15)**: Escalate to Project Sponsor  
- **Critical Risk (16-25)**: Escalate to Executive Sponsor

---

## 6. Organizational Context for Risk Management

### Enterprise Environmental Factors (EEFs) - Requires Organizational Input

**Industry Risk Factors:**  
- [TBD - Organizational Input Required]: Industry-specific regulations and compliance requirements
- [TBD - Organizational Input Required]: Market volatility and competitive landscape
- [TBD - Organizational Input Required]: Technology standards and industry best practices

**Organizational Risk Tolerance:**  
- [TBD - Organizational Input Required]: Organization's appetite for technical risk
- [TBD - Organizational Input Required]: Budget variance tolerance levels
- [TBD - Organizational Input Required]: Schedule flexibility and delivery expectations

### Organizational Process Assets (OPAs) - Requires Organizational Input

**Risk Management Processes:**  
- [TBD - Organizational Input Required]: Standard risk assessment methodologies
- [TBD - Organizational Input Required]: Risk escalation procedures and approval workflows
- [TBD - Organizational Input Required]: Historical risk data from similar projects

**Templates and Tools:**  
- [TBD - Organizational Input Required]: Organization's standard risk register template
- [TBD - Organizational Input Required]: Risk assessment software and tools
- [TBD - Organizational Input Required]: Reporting templates and communication standards

---

## 7. Instructions for Risk Register Completion

### Data Collection Process

1. **Stakeholder Risk Workshops**: Conduct structured brainstorming sessions with project team and key stakeholders
2. **Historical Analysis**: Review lessons learned from similar projects within the organization
3. **Expert Judgment**: Consult with subject matter experts in relevant domains
4. **Checklist Review**: Use PMBOK and industry-specific risk checklists for comprehensive coverage

### Risk Assessment Guidelines

1. **Probability Assessment**: Base on historical data, expert judgment, and project-specific factors
2. **Impact Assessment**: Consider effects on scope, schedule, cost, quality, and strategic objectives
3. **Mitigation Strategy Development**: Ensure strategies are specific, measurable, and actionable
4. **Owner Assignment**: Assign to individuals with authority and capability to manage the risk

### Ongoing Risk Management

1. **Regular Updates**: Review and update risk register at least weekly during active project phases
2. **New Risk Identification**: Continuously scan for emerging risks throughout project lifecycle
3. **Risk Closure**: Document lessons learned when risks are closed or realized
4. **Communication**: Maintain transparent risk communication with all stakeholders

---

*This Risk Register was intelligently pre-populated by analyzing project context, scope, and stakeholder information. Please review, validate, and complete the organizational sections to ensure comprehensive risk coverage.*

---

**Document Control:**  
- **Version**: 1.0  
- **Last Updated**: ${new Date().toISOString()}  
- **Next Review**: [Schedule based on project phase]  
- **Owner**: [Project Manager Name]  
- **Approver**: [Project Sponsor Name]`;
  }
}
